In [10]:
import os
import pandas as pd
from datetime import datetime
import pydicom
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import csv
import re


# make sure to have dcm2niix installed
from utils.dcm2niix import *

!which dcm2niix


BERNER_DATEN_PATH='/nasdata/Berner_Daten/Other_Side_Bilddaten'
# read
ANALYSIS_PATH='/home/bule/berner_daten_analyse/data'

APP_DATA_PATH = '/home/bule/berner_daten_analyse/apps/app_manual_preselection'

/usr/local/bin/dcm2niix

In [ ]:
# Widgets
patient_dropdown = Dropdown(options=df['patient_id'].unique(), description='Patient:')
sequence_dropdown = Dropdown(description='Sequence:')
sequences_output = Output()
output = Output()

# Update sequence dropdown and display all entries for the selected patient
def update_sequences(*args):
    patient_id = patient_dropdown.value
    patient_data = df[df['patient_id'] == patient_id]
    sequence_dropdown.options = patient_data['study_id'].values

    with sequences_output:
        clear_output(wait=True)
        display(patient_data[['study_id', 'file_path', 'modality']])

# Display the selected modality visualization
def display_modality():
    clear_output(wait=True)
    patient_id = patient_dropdown.value
    study_id = sequence_dropdown.value

    if study_id is None:
        return

    row = df[(df['patient_id'] == patient_id) & (df['study_id'] == study_id)].iloc[0]
    file_path = row['file_path']
    modality = row['modality']

    # Load NIfTI file
    img = nib.load(file_path)
    data = img.get_fdata()

    def view_slice_dwi(slice_idx):
        clear_output(wait=True)
        plt.figure(figsize=(3, 3))
        plt.imshow(data[:, :, slice_idx, 1].squeeze(), cmap="gray", origin="lower")
        plt.title(f"Slice {slice_idx}")
        plt.axis("off")
        plt.show()

    def view_slice(slice_idx):
        clear_output(wait=True)
        plt.figure(figsize=(3, 3))
        plt.imshow(data[:, :, slice_idx].squeeze(), cmap="gray", origin="lower")
        plt.title(f"Slice {slice_idx}")
        plt.axis("off")
        plt.show()

    if modality == 'dwi':
        slider = IntSlider(min=0, max=data.shape[2] - 1, step=1, value=0)
        interactive_plot = interactive(view_slice_dwi, slice_idx=slider)
    elif modality == 't1':
        slider = IntSlider(min=0, max=data.shape[2] - 1, step=1, value=0)
        interactive_plot = interactive(view_slice, slice_idx=slider)

    display(interactive_plot)

# Link dropdowns and output
patient_dropdown.observe(update_sequences, names='value')
sequence_dropdown.observe(lambda change: display_modality(), names='value')

# Initial population of sequences
update_sequences()

# Layout
display(VBox([Label('Select Patient and Sequence:'), patient_dropdown, sequences_output, sequence_dropdown, output]))

### first try with manual selection neg / pos

In [ ]:
dwi_t1_all_df=pd.read_csv(os.path.join(ANALYSIS_PATH,"dwi_t1_all.csv"))
dwi_t1_all_df.sort_values(by='Patient_ID',inplace=True)
dwi_t1_all_df.head()

- sort paths

In [ ]:
NII_TARGET_PATH = '/home/bule/berner_daten_analyse/data/nifti_first_try'

source_dcm_sequences = [os.path.join('/',*path.split('/')[:-1]) for path in dwi_t1_all_df['Full_Path']]
source_dcm_sequences = list(set([os.path.join('/',path) for path in source_dcm_sequences]))
print(source_dcm_sequences[0])

target_nii_sequences= [os.path.join(*path.split('/')[4:]) for path in source_dcm_sequences]
target_nii_sequences= [os.path.join(NII_TARGET_PATH,path) for path in target_nii_sequences]

print(target_nii_sequences[0])

- convert all files

In [ ]:
#process_directories(source_dcm_sequences, target_nii_sequences)

### Second try with dicom_tags on image for dwi and t1 from manual selection

In [3]:
dwi_t1_df_2=pd.read_csv(os.path.join(ANALYSIS_PATH,"dwi_t1_df_2.csv"))
dwi_t1_df_2.sort_values(by='Patient_ID',inplace=True)
dwi_t1_df_2.head()

,Patient_ID,Study_ID,Sequence_ID,File_Name,Full_Path,Date,Sequence_ID_split,Modality
64,76813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,21.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2017-06-14,ep2d_diff_M128_b0_1000_DIN,DWI
65,76813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,22.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2017-06-14,ep2d_diff_M128_b0_1000_DIN,DWI
66,76813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,23.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2017-06-14,ep2d_diff_M128_b0_1000_DIN,DWI
67,76813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,24.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2017-06-14,ep2d_diff_M128_b0_1000_DIN,DWI
68,76813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,25.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2017-06-14,ep2d_diff_M128_b0_1000_DIN,DWI

In [12]:
NII_TARGET_PATH = '/home/bule/berner_daten_analyse/data/nifti_second_try'
LOG_PATH = os.path.join(NII_TARGET_PATH, 'conversion_errors.log')

source_dcm_sequences = [os.path.join('/',*path.split('/')[:-1]) for path in dwi_t1_df_2['Full_Path']]
source_dcm_sequences = list(set([os.path.join('/',path) for path in source_dcm_sequences]))
print(source_dcm_sequences[1])

target_nii_sequences= [os.path.join(*path.split('/')[4:]) for path in source_dcm_sequences]
target_nii_sequences= [os.path.join(NII_TARGET_PATH,path) for path in target_nii_sequences]

print(target_nii_sequences[0])

/nasdata/Berner_Daten/Other_Side_Bilddaten/0012524182/20150113_3588770/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2015011320513753223269825.0.0.0
/home/bule/berner_daten_analyse/data/nifti_second_try/0013727036/20171006_4382923/t1_se_tra__1.3.12.2.1107.5.2.41.169589.2017100613315827522264852.0.0.0

In [ ]:
#process_directories(source_dcm_sequences, target_nii_sequences,log_path=LOG_PATH)# ~ 11 mins

In [ ]:
dwi_t1_df_2

# Try with own small selection

In [7]:
NII_TARGET_PATH = '/home/bule/berner_daten_analyse/data/nifti_pascal_selection_try'
LOG_PATH = os.path.join(NII_TARGET_PATH, 'conversion_errors_pascal_selection.log')

In [3]:
import json
with open(os.path.join(APP_DATA_PATH,'pascal_sequences.json')) as json_file:
    selection_pascal_dict = json.load(json_file)

rows = []
for patid, selection_dict in selection_pascal_dict.items():
    for modality, sequences in selection_dict.items():
        for sequence in sequences:
            study_id, sequence_id = sequence.split('/')
            rows.append({
                'Patient_ID': patid,
                'Study_ID': study_id,
                'Sequence_ID': sequence_id,
                'Modality': modality,
                'Labeller': 'Pascal'  
            })
selection_pascal_df = pd.DataFrame(rows)
print(selection_pascal_df)

     Patient_ID          Study_ID  \
0    0000076813  20170614_4361718
1    0000076813  20170929_4371316
2    0000442968  20151109_3835318
3    0000442968  20151109_3835318
4    0000481858  20121025_3013771
..          ...               ...
247  0007202016  20120911_2984878
248  0007335466  20160906_4097302
249  0007335466  20160906_4097302
250  0007341989  20140116_3316435
251  0007341989  20140116_3316435

                                           Sequence_ID Modality Labeller
0    ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....      dwi   Pascal
1    t1_se_tra__1.3.12.2.1107.5.2.41.169589.2017092...       t1   Pascal
2    ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30...      dwi   Pascal
3    t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.201...       t1   Pascal
4    resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12....      dwi   Pascal
..                                                 ...      ...      ...
247  t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.201209...       t1   Pascal
248  ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30...      dwi   Pascal
249  Tirm_tra_fs_TI_2500__1.3.12.2.1107.5.2.30.2727...       t1   Pascal
250  ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30...      dwi   Pascal
251  t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.201...       t1   Pascal

[252 rows x 5 columns]

In [12]:
selection_pascal_df['Sequence_path']=selection_pascal_df.apply(lambda x: os.path.join(BERNER_DATEN_PATH,x['Patient_ID'],x['Study_ID'],x['Sequence_ID']),axis=1)
selection_pascal_df

,Patient_ID,Study_ID,Sequence_ID,Modality,Labeller,Sequence_path
0,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,dwi,Pascal,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...
1,0000076813,20170929_4371316,t1_se_tra__1.3.12.2.1107.5.2.41.169589.2017092...,t1,Pascal,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...
2,0000442968,20151109_3835318,ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30...,dwi,Pascal,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...
3,0000442968,20151109_3835318,t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.201...,t1,Pascal,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...
4,0000481858,20121025_3013771,resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12....,dwi,Pascal,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...
...,...,...,...,...,...,...
247,0007202016,20120911_2984878,t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.201209...,t1,Pascal,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...
248,0007335466,20160906_4097302,ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30...,dwi,Pascal,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...
249,0007335466,20160906_4097302,Tirm_tra_fs_TI_2500__1.3.12.2.1107.5.2.30.2727...,t1,Pascal,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...
250,0007341989,20140116_3316435,ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30...,dwi,Pascal,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...
251,0007341989,20140116_3316435,t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.201...,t1,Pascal,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...

In [13]:





source_dcm_sequences=list(selection_pascal_df['Sequence_path'])
print(source_dcm_sequences[0])

target_nii_sequences= [os.path.join(*path.split('/')[4:]) for path in source_dcm_sequences]
target_nii_sequences= [os.path.join(NII_TARGET_PATH,path) for path in target_nii_sequences]
print(target_nii_sequences[0])

/nasdata/Berner_Daten/Other_Side_Bilddaten/0000076813/20170614_4361718/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2017061416562196724753041.0.0.0
/home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000076813/20170614_4361718/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2017061416562196724753041.0.0.0

In [14]:
process_directories(source_dcm_sequences, target_nii_sequences,log_path=LOG_PATH)# ~ 11 mins

Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 50 DICOM file(s)
Warning: Discrepancy between reported (3.5s) and estimated (2.63562s) repetition time (issue 560).
Convert 50 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000076813/20170614_4361718/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2017061416562196724753041.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40186.2017061416562196724753041.0.0.0_ep2d_diff_M128_b0_1000_DIN_20170614164701_6 (128x128x25x2)
Conversion required 0.294605 seconds (0.228405 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000076813/20170614_4361718/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2017061416562196724753041.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000076813/20170614_4361718/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2017061416562196724753041.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 29 DICOM file(s)
Warning: interpolated protocol 't1_se_tra' may be unsuitable for dwidenoise/mrdegibbs. /nasdata/Berner_Daten/Other_Side_Bilddaten/0000076813/20170929_4371316/t1_se_tra__1.3.12.2.1107.5.2.41.169589.2017092912262239073557517.0.0.0/1.dcm
Convert 29 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000076813/20170929_4371316/t1_se_tra__1.3.12.2.1107.5.2.41.169589.2017092912262239073557517.0.0.0/t1_se_tra_1.3.12.2.1107.5.2.41.169589.2017092912262239073557517.0.0.0_t1_se_tra_20170929120431_19 (600x640x29x1)
Conversion required 1.750983 seconds (1.654857 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000076813/20170929_4371316/t1_se_tra__1.3.12.2.1107.5.2.41.169589.2017092912262239073557517.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000076813/20170929_4371316/t1_se_tra__1.3.12.2.1107.5.2.41.169589.2017092912262239073557517.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 38 DICOM file(s)
Warning: Discrepancy between reported (3s) and estimated (2.25875s) repetition time (issue 560).
Convert 38 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000442968/20151109_3835318/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015110920165992101992192.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2015110920165992101992192.0.0.0_ep2d_diff_3scan_trace_p2_20151109201528_2 (192x192x19x2)
Conversion required 0.353937 seconds (0.288264 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000442968/20151109_3835318/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015110920165992101992192.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000442968/20151109_3835318/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015110920165992101992192.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000442968/20151109_3835318/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2015110920312888633402583.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2015110920312888633402583.0.0.0_t1_se_r_tra_KM_20151109201528_14 (224x256x24x1)
Conversion required 0.359965 seconds (0.248115 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000442968/20151109_3835318/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2015110920312888633402583.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000442968/20151109_3835318/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2015110920312888633402583.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 40 DICOM file(s)
Warning: Discrepancy between reported (4.1s) and estimated (86.11s) repetition time (issue 560).
Warning: Volume 1 appears to be derived image ADC/Isotropic (non-zero b-value with zero vector length)
Convert 40 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000481858/20121025_3013771/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.2012102507535097175006177.0.0.0/resolve_3scan_trace_tra_176_p2_TRACEW_1.3.12.2.1107.5.2.18.41437.2012102507535097175006177.0.0.0_resolve_3scan_trace_tra_176_p2_20121025075220_2 (176x176x20x2)
Conversion required 0.423719 seconds (0.314290 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000481858/20121025_3013771/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.2012102507535097175006177.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000481858/20121025_3013771/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.2012102507535097175006177.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000481858/20121025_3013771/t2_blade_tra_320__1.3.12.2.1107.5.2.18.41437.2012102507574223992008744.0.0.0/t2_blade_tra_320_1.3.12.2.1107.5.2.18.41437.2012102507574223992008744.0.0.0_t2_blade_tra_320_20121025075220_4 (320x320x24x1)
Conversion required 0.524291 seconds (0.433667 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000481858/20121025_3013771/t2_blade_tra_320__1.3.12.2.1107.5.2.18.41437.2012102507574223992008744.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000481858/20121025_3013771/t2_blade_tra_320__1.3.12.2.1107.5.2.18.41437.2012102507574223992008744.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 44 DICOM file(s)
Warning: Discrepancy between reported (3.5s) and estimated (2.63562s) repetition time (issue 560).
Convert 44 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000516341/20160211_3914130/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2016021109502693022615340.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40186.2016021109502693022615340.0.0.0_ep2d_diff_M128_b0_1000_DIN_20160211094700_2 (128x128x22x2)
Conversion required 0.334340 seconds (0.229919 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000516341/20160211_3914130/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2016021109502693022615340.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000516341/20160211_3914130/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2016021109502693022615340.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000516341/20160211_3914130/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40186.2016021110060759985926913.0.0.0/t1_fl2d_tra_1.3.12.2.1107.5.2.36.40186.2016021110060759985926913.0.0.0_t1_fl2d_tra_20160211094700_12 (324x384x24x1)
Conversion required 0.563158 seconds (0.498323 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000516341/20160211_3914130/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40186.2016021110060759985926913.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000516341/20160211_3914130/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40186.2016021110060759985926913.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 58 DICOM file(s)
Warning: Discrepancy between reported (6.08s) and estimated (121.607s) repetition time (issue 560).
Warning: Volume 1 appears to be derived image ADC/Isotropic (non-zero b-value with zero vector length)
Convert 58 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000607681/20170707_4385986/resolve_4scan_trace_tra_diff_TRACEW__1.3.12.2.1107.5.2.19.45799.2017070716442627892817331.0.0.0/resolve_4scan_trace_tra_diff_TRACEW_1.3.12.2.1107.5.2.19.45799.2017070716442627892817331.0.0.0_resolve_4scan_trace_tra_diff_20170707162658_14 (192x192x29x2)
Conversion required 0.600034 seconds (0.481109 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000607681/20170707_4385986/resolve_4scan_trace_tra_diff_TRACEW__1.3.12.2.1107.5.2.19.45799.2017070716442627892817331.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000607681/20170707_4385986/resolve_4scan_trace_tra_diff_TRACEW__1.3.12.2.1107.5.2.19.45799.2017070716442627892817331.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 30 DICOM file(s)
Convert 30 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000607681/20170707_4385986/t1_fl2d_tra__1.3.12.2.1107.5.2.19.45799.2017070716281962733113644.0.0.0/t1_fl2d_tra_1.3.12.2.1107.5.2.19.45799.2017070716281962733113644.0.0.0_t1_fl2d_tra_20170707162658_5 (320x320x30x1)
Conversion required 0.625914 seconds (0.552453 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000607681/20170707_4385986/t1_fl2d_tra__1.3.12.2.1107.5.2.19.45799.2017070716281962733113644.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000607681/20170707_4385986/t1_fl2d_tra__1.3.12.2.1107.5.2.19.45799.2017070716281962733113644.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 50 DICOM file(s)
Warning: Discrepancy between reported (3.5s) and estimated (2.635s) repetition time (issue 560).
Convert 50 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000653853/20161216_4193466/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2016121611003455620444483.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40186.2016121611003455620444483.0.0.0_ep2d_diff_M128_b0_1000_DIN_20161216105853_2 (128x128x25x2)
Conversion required 0.322523 seconds (0.229235 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000653853/20161216_4193466/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2016121611003455620444483.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000653853/20161216_4193466/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2016121611003455620444483.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000653853/20161216_4193466/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40186.2016121611140451926256798.0.0.0/t1_fl2d_tra_1.3.12.2.1107.5.2.36.40186.2016121611140451926256798.0.0.0_t1_fl2d_tra_20161216105853_14 (324x384x24x1)
Conversion required 0.541691 seconds (0.479760 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000653853/20161216_4193466/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40186.2016121611140451926256798.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000653853/20161216_4193466/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40186.2016121611140451926256798.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 50 DICOM file(s)
Warning: Discrepancy between reported (3.5s) and estimated (2.63562s) repetition time (issue 560).
Convert 50 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000744018/20140321_3307663/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2014032112104737923044060.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40186.2014032112104737923044060.0.0.0_ep2d_diff_M128_b0_1000_DIN_20140321120529_2 (128x128x25x2)
Conversion required 0.349623 seconds (0.239691 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000744018/20140321_3307663/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2014032112104737923044060.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000744018/20140321_3307663/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2014032112104737923044060.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000744018/20140321_3307663/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40186.2014032112310734751955831.0.0.0/t1_fl2d_tra_1.3.12.2.1107.5.2.36.40186.2014032112310734751955831.0.0.0_t1_fl2d_tra_20140321120529_12 (324x384x24x1)
Conversion required 0.579199 seconds (0.516197 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000744018/20140321_3307663/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40186.2014032112310734751955831.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000744018/20140321_3307663/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40186.2014032112310734751955831.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 50 DICOM file(s)
Warning: Discrepancy between reported (3.5s) and estimated (2.63562s) repetition time (issue 560).
Convert 50 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000768081/20130110_3061277/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2013011009244276086119640.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2013011009244276086119640.0.0.0_ep2d_diff_M128_b0_1000_DIN_20130110092000_2 (128x128x25x2)
Conversion required 0.343906 seconds (0.243190 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000768081/20130110_3061277/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2013011009244276086119640.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000768081/20130110_3061277/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2013011009244276086119640.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000768081/20130110_3061277/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2013011009423440374031221.0.0.0/t1_fl2d_tra_1.3.12.2.1107.5.2.36.40270.2013011009423440374031221.0.0.0_t1_fl2d_tra_20130110092000_14 (324x384x24x1)
Conversion required 0.523449 seconds (0.459753 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000768081/20130110_3061277/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2013011009423440374031221.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000768081/20130110_3061277/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2013011009423440374031221.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 50 DICOM file(s)
Warning: Discrepancy between reported (3.5s) and estimated (2.63562s) repetition time (issue 560).
Convert 50 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000801402/20161123_4171427/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2016112315454677328107737.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2016112315454677328107737.0.0.0_ep2d_diff_M128_b0_1000_DIN_20161123154259_2 (128x128x25x2)
Conversion required 0.357823 seconds (0.257313 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000801402/20161123_4171427/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2016112315454677328107737.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000801402/20161123_4171427/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2016112315454677328107737.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000801402/20161123_4171427/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2016112316100455885928528.0.0.0/t1_fl2d_tra_1.3.12.2.1107.5.2.36.40270.2016112316100455885928528.0.0.0_t1_fl2d_tra_20161123154259_20 (324x384x24x1)
Conversion required 0.522178 seconds (0.459510 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000801402/20161123_4171427/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2016112316100455885928528.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000801402/20161123_4171427/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2016112316100455885928528.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 50 DICOM file(s)
Warning: Discrepancy between reported (3.5s) and estimated (2.63562s) repetition time (issue 560).
Convert 50 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000830267/20140331_3374880/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.20140331175722547933095.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.20140331175722547933095.0.0.0_ep2d_diff_M128_b0_1000_DIN_20140331175529_2 (128x128x25x2)
Conversion required 0.333425 seconds (0.234824 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000830267/20140331_3374880/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.20140331175722547933095.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000830267/20140331_3374880/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.20140331175722547933095.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000830267/20140331_3374880/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2014033118100679714144595.0.0.0/t1_fl2d_tra_1.3.12.2.1107.5.2.36.40270.2014033118100679714144595.0.0.0_t1_fl2d_tra_20140331175529_16 (270x320x24x1)
Conversion required 0.371771 seconds (0.316069 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000830267/20140331_3374880/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2014033118100679714144595.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000830267/20140331_3374880/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2014033118100679714144595.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 40 DICOM file(s)
Warning: Discrepancy between reported (4.1s) and estimated (86.1075s) repetition time (issue 560).
Warning: Volume 1 appears to be derived image ADC/Isotropic (non-zero b-value with zero vector length)
Convert 40 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000842389/20140312_3359892/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.2014031212351314054924900.0.0.0/resolve_3scan_trace_tra_176_p2_TRACEW_1.3.12.2.1107.5.2.18.41437.2014031212351314054924900.0.0.0_resolve_3scan_trace_tra_176_p2_20140312123324_2 (176x176x20x2)
Conversion required 0.461357 seconds (0.320097 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000842389/20140312_3359892/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.2014031212351314054924900.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000842389/20140312_3359892/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.2014031212351314054924900.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000842389/20140312_3359892/t1_tse_r_tra__1.3.12.2.1107.5.2.18.41437.2014031212500855091136174.0.0.0/t1_tse_r_tra_1.3.12.2.1107.5.2.18.41437.2014031212500855091136174.0.0.0_t1_tse_r_tra_20140312123324_11 (224x256x24x1)
Conversion required 0.313746 seconds (0.260153 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0000842389/20140312_3359892/t1_tse_r_tra__1.3.12.2.1107.5.2.18.41437.2014031212500855091136174.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0000842389/20140312_3359892/t1_tse_r_tra__1.3.12.2.1107.5.2.18.41437.2014031212500855091136174.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 50 DICOM file(s)

Error: Input folder invalid: b1000__1.3.46.670589.11.70452.5.0.7948.2017022110231878000
/bin/sh: 1: Syntax error: "(" unexpected

Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 42 DICOM file(s)
Warning: Discrepancy between reported (3.3s) and estimated (2.485s) repetition time (issue 560).
Convert 42 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001615629/20170624_4371304/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2017062414592963388363156.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2017062414592963388363156.0.0.0_ep2d_diff_3scan_trace_p2_20170624145813_2 (192x192x21x2)
Conversion required 0.465894 seconds (0.331665 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001615629/20170624_4371304/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2017062414592963388363156.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001615629/20170624_4371304/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2017062414592963388363156.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Warning: only processing last of 7 input files (recompile with 'myEnableMultipleInputs' to recursively process multiple files)
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001615629/20170623_4370547/t1 mpr tra mk__1.3.12.2.1107.5.2.18.41437.30000017062305304934200011876 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001615629/20170623_4370547/t1 mpr tra mk__1.3.12.2.1107.5.2.18.41437.30000017062305304934200011876

Error: Input folder invalid: mk__1.3.12.2.1107.5.2.18.41437.30000017062305304934200011876

Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 38 DICOM file(s)
Warning: Discrepancy between reported (3s) and estimated (2.25938s) repetition time (issue 560).
Convert 38 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001657011/20160313_3941113/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016031316312397417462335.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2016031316312397417462335.0.0.0_ep2d_diff_3scan_trace_p2_20160313162717_2 (192x192x19x2)
Conversion required 0.402230 seconds (0.311745 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001657011/20160313_3941113/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016031316312397417462335.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001657011/20160313_3941113/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016031316312397417462335.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001657011/20160313_3941113/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2016031316461074921772726.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2016031316461074921772726.0.0.0_t1_se_r_tra_KM_20160313162717_14 (224x256x24x1)
Conversion required 0.350053 seconds (0.276548 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001657011/20160313_3941113/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2016031316461074921772726.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001657011/20160313_3941113/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2016031316461074921772726.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 38 DICOM file(s)
Warning: Discrepancy between reported (3s) and estimated (2.25938s) repetition time (issue 560).
Convert 38 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001679589/20160714_4050235/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016071412100665705553359.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2016071412100665705553359.0.0.0_ep2d_diff_3scan_trace_p2_20160714120359_2 (192x192x19x2)
Conversion required 0.388067 seconds (0.297390 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001679589/20160714_4050235/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016071412100665705553359.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001679589/20160714_4050235/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016071412100665705553359.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001679589/20160714_4050235/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2016071412250424413864535.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2016071412250424413864535.0.0.0_t1_se_r_tra_KM_20160714120359_14 (224x256x24x1)
Conversion required 0.331985 seconds (0.226076 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001679589/20160714_4050235/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2016071412250424413864535.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001679589/20160714_4050235/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2016071412250424413864535.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 40 DICOM file(s)
Warning: Discrepancy between reported (4.1s) and estimated (86.1075s) repetition time (issue 560).
Warning: Volume 1 appears to be derived image ADC/Isotropic (non-zero b-value with zero vector length)
Convert 40 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001728245/20160602_4011937/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.2016060213155013546442902.0.0.0/resolve_3scan_trace_tra_176_p2_TRACEW_1.3.12.2.1107.5.2.18.41437.2016060213155013546442902.0.0.0_resolve_3scan_trace_tra_176_p2_20160602131359_2 (176x176x20x2)
Conversion required 0.288521 seconds (0.258701 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001728245/20160602_4011937/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.2016060213155013546442902.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001728245/20160602_4011937/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.2016060213155013546442902.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001728245/20160602_4011937/t1_tse_r_tra__1.3.12.2.1107.5.2.18.41437.2016060213432648096957071.0.0.0/t1_tse_r_tra_1.3.12.2.1107.5.2.18.41437.2016060213432648096957071.0.0.0_t1_tse_r_tra_20160602131359_15 (224x256x24x1)
Conversion required 0.273405 seconds (0.227375 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001728245/20160602_4011937/t1_tse_r_tra__1.3.12.2.1107.5.2.18.41437.2016060213432648096957071.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001728245/20160602_4011937/t1_tse_r_tra__1.3.12.2.1107.5.2.18.41437.2016060213432648096957071.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 50 DICOM file(s)
Warning: Discrepancy between reported (3.5s) and estimated (2.63562s) repetition time (issue 560).
Convert 50 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001746421/20120305_2868060/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2012030520305325508491476.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2012030520305325508491476.0.0.0_ep2d_diff_M128_b0_1000_DIN_20120305202905_2 (128x128x25x2)
Conversion required 0.273614 seconds (0.200965 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001746421/20120305_2868060/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2012030520305325508491476.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001746421/20120305_2868060/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2012030520305325508491476.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001746421/20120305_2868060/t2_blade_tra_5mm__1.3.12.2.1107.5.2.36.40270.2012030520334641106693684.0.0.0/t2_blade_tra_5mm_1.3.12.2.1107.5.2.36.40270.2012030520334641106693684.0.0.0_t2_blade_tra_5mm_20120305202905_4 (320x320x24x1)
Conversion required 0.517132 seconds (0.416619 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001746421/20120305_2868060/t2_blade_tra_5mm__1.3.12.2.1107.5.2.36.40270.2012030520334641106693684.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001746421/20120305_2868060/t2_blade_tra_5mm__1.3.12.2.1107.5.2.36.40270.2012030520334641106693684.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 57 DICOM file(s)
Warning: Discrepancy between reported (3s) and estimated (2.25906s) repetition time (issue 560).
Convert 57 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001775707/20150301_3626826/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015030113162725907554790.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2015030113162725907554790.0.0.0_ep2d_diff_3scan_trace_p2_20150301131409_2 (192x192x19x3)
Conversion required 0.564297 seconds (0.419997 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001775707/20150301_3626826/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015030113162725907554790.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001775707/20150301_3626826/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015030113162725907554790.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001775707/20150301_3626826/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2015030113314827801166636.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2015030113314827801166636.0.0.0_t1_se_r_tra_KM_20150301131409_15 (224x256x24x1)
Conversion required 0.317641 seconds (0.245063 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001775707/20150301_3626826/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2015030113314827801166636.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001775707/20150301_3626826/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2015030113314827801166636.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 40 DICOM file(s)
Warning: Discrepancy between reported (4.1s) and estimated (86.1075s) repetition time (issue 560).
Warning: Volume 1 appears to be derived image ADC/Isotropic (non-zero b-value with zero vector length)
Convert 40 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001806920/20150220_3620682/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.2015022017104842881727445.0.0.0/resolve_3scan_trace_tra_176_p2_TRACEW_1.3.12.2.1107.5.2.18.41437.2015022017104842881727445.0.0.0_resolve_3scan_trace_tra_176_p2_20150220170923_2 (176x176x20x2)
Conversion required 0.427617 seconds (0.324193 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001806920/20150220_3620682/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.2015022017104842881727445.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001806920/20150220_3620682/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.2015022017104842881727445.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001806920/20150220_3620682/t2_tse_tra_5mm__1.3.12.2.1107.5.2.18.41437.2015022017154887998230002.0.0.0/t2_tse_tra_5mm_1.3.12.2.1107.5.2.18.41437.2015022017154887998230002.0.0.0_t2_tse_tra_5mm_20150220170923_4 (336x384x24x1)
Conversion required 0.653377 seconds (0.535279 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001806920/20150220_3620682/t2_tse_tra_5mm__1.3.12.2.1107.5.2.18.41437.2015022017154887998230002.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001806920/20150220_3620682/t2_tse_tra_5mm__1.3.12.2.1107.5.2.18.41437.2015022017154887998230002.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 38 DICOM file(s)
Warning: Discrepancy between reported (3s) and estimated (2.25938s) repetition time (issue 560).
Convert 38 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001829939/20150718_3741531/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015071807190941239701338.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2015071807190941239701338.0.0.0_ep2d_diff_3scan_trace_p2_20150718071712_2 (192x192x19x2)
Conversion required 0.509022 seconds (0.378270 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001829939/20150718_3741531/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015071807190941239701338.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001829939/20150718_3741531/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015071807190941239701338.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001829939/20150718_3741531/t2_tse_tra_448__1.3.12.2.1107.5.2.30.27272.2015071807383864963612622.0.0.0/t2_tse_tra_448_1.3.12.2.1107.5.2.30.27272.2015071807383864963612622.0.0.0_t2_tse_tra_448_20150718071712_15 (390x448x24x1)
Conversion required 0.605321 seconds (0.590691 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001829939/20150718_3741531/t2_tse_tra_448__1.3.12.2.1107.5.2.30.27272.2015071807383864963612622.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001829939/20150718_3741531/t2_tse_tra_448__1.3.12.2.1107.5.2.30.27272.2015071807383864963612622.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 40 DICOM file(s)
Warning: Discrepancy between reported (4.1s) and estimated (86.1075s) repetition time (issue 560).
Warning: Volume 1 appears to be derived image ADC/Isotropic (non-zero b-value with zero vector length)
Convert 40 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001870394/20131101_3264798/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.201311011136166347429830.0.0.0/resolve_3scan_trace_tra_176_p2_TRACEW_1.3.12.2.1107.5.2.18.41437.201311011136166347429830.0.0.0_resolve_3scan_trace_tra_176_p2_20131101113433_2 (176x176x20x2)
Conversion required 0.317925 seconds (0.294930 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001870394/20131101_3264798/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.201311011136166347429830.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001870394/20131101_3264798/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.201311011136166347429830.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001870394/20131101_3264798/t1_tse_r_tra__1.3.12.2.1107.5.2.18.41437.2013110111585456706641395.0.0.0/t1_tse_r_tra_1.3.12.2.1107.5.2.18.41437.2013110111585456706641395.0.0.0_t1_tse_r_tra_20131101113433_12 (224x256x24x1)
Conversion required 0.320236 seconds (0.240785 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001870394/20131101_3264798/t1_tse_r_tra__1.3.12.2.1107.5.2.18.41437.2013110111585456706641395.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001870394/20131101_3264798/t1_tse_r_tra__1.3.12.2.1107.5.2.18.41437.2013110111585456706641395.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 50 DICOM file(s)
Warning: Discrepancy between reported (3.5s) and estimated (2.635s) repetition time (issue 560).
Convert 50 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001922173/20170622_4369392/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.201706221248259974123766.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.201706221248259974123766.0.0.0_ep2d_diff_M128_b0_1000_DIN_20170622124631_2 (128x128x25x2)
Conversion required 0.231164 seconds (0.197758 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001922173/20170622_4369392/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.201706221248259974123766.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001922173/20170622_4369392/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.201706221248259974123766.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001922173/20170622_4369392/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2017062213055451488835266.0.0.0/t1_fl2d_tra_1.3.12.2.1107.5.2.36.40270.2017062213055451488835266.0.0.0_t1_fl2d_tra_20170622124631_14 (324x384x24x1)
Conversion required 0.557110 seconds (0.420589 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001922173/20170622_4369392/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2017062213055451488835266.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001922173/20170622_4369392/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2017062213055451488835266.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 50 DICOM file(s)
Warning: Discrepancy between reported (3.5s) and estimated (2.63562s) repetition time (issue 560).
Convert 50 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001926713/20151023_3821340/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2015102312112178347286360.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2015102312112178347286360.0.0.0_ep2d_diff_M128_b0_1000_DIN_20151023120227_5 (128x128x25x2)
Conversion required 0.300976 seconds (0.220683 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001926713/20151023_3821340/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2015102312112178347286360.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001926713/20151023_3821340/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2015102312112178347286360.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001926713/20151023_3821340/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2015102312234937105997734.0.0.0/t1_fl2d_tra_1.3.12.2.1107.5.2.36.40270.2015102312234937105997734.0.0.0_t1_fl2d_tra_20151023120227_17 (324x384x24x1)
Conversion required 0.589363 seconds (0.478444 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0001926713/20151023_3821340/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2015102312234937105997734.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0001926713/20151023_3821340/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2015102312234937105997734.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 57 DICOM file(s)
Warning: Discrepancy between reported (3s) and estimated (2.25906s) repetition time (issue 560).
Convert 57 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0002013010/20131012_3249790/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2013101202134197237601340.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2013101202134197237601340.0.0.0_ep2d_diff_3scan_trace_p2_20131012021144_2 (192x192x19x3)
Conversion required 0.578473 seconds (0.435417 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0002013010/20131012_3249790/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2013101202134197237601340.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0002013010/20131012_3249790/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2013101202134197237601340.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 24 DICOM file(s)
Convert 24 DICOM as /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0002013010/20131012_3249790/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2013101202290617655413536.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2013101202290617655413536.0.0.0_t1_se_r_tra_KM_20131012021144_14 (224x256x24x1)
Conversion required 0.337105 seconds (0.226399 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0002013010/20131012_3249790/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2013101202290617655413536.0.0.0 -> /home/bule/berner_daten_analyse/data/nifti_pascal_selection_try/0002013010/20131012_3249790/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2013101202290617655413536.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220505  GCC11.4.0 x86-64 (64-bit Linux)
Found 50 DICOM file(s)
Warning: Discrepancy between reported (3.5s) and estimated (2.63562s) repetition time (issue 560).

## Third try with selection from hakim/ Julian / martin  via browsertool

In [ ]:
NII_TARGET_PATH = '/home/bule/berner_daten_analyse/data/nifti_third_try'
LOG_PATH = os.path.join(NII_TARGET_PATH, 'conversion_errors_3.log')

In [11]:
dwi_t1_df_3=pd.read_csv(os.path.join(ANALYSIS_PATH,"dwi_t1_df_3.csv"))
dwi_t1_df_3.sort_values(by='Patient_ID',inplace=True)
dwi_t1_df_3.head()

FileNotFoundError: [Errno 2] No such file or directory: '/home/bule/berner_daten_analyse/data/dwi_t1_df_3.csv'

In [ ]:
NII_TARGET_PATH = '/home/bule/berner_daten_analyse/data/nifti_third_try'
LOG_PATH = os.path.join(NII_TARGET_PATH, 'conversion_errors_3.log')

source_dcm_sequences = [os.path.join('/',*path.split('/')[:-1]) for path in dwi_t1_df_2['Full_Path']]
source_dcm_sequences = list(set([os.path.join('/',path) for path in source_dcm_sequences]))
print(source_dcm_sequences[0])

target_nii_sequences= [os.path.join(*path.split('/')[4:]) for path in source_dcm_sequences]
target_nii_sequences= [os.path.join(NII_TARGET_PATH,path) for path in target_nii_sequences]

print(target_nii_sequences[0])

In [ ]:
#process_directories(source_dcm_sequences, target_nii_sequences,log_path=LOG_PATH)# ~ 11 mins