### This file creates the file for highlighting the sequences for the adc selection app for the segmentation -> used for concepts

# BERNER

- setz up selectin app
- read manual selecetion by rater1 
- check if all 297 hav an according adc
- save df

In [ ]:
import sys
sys.path.append("/home/bule/berner_daten_analyse")

# quickhack -> move this file to the location wher you want the processed niftis to be stored

In [3]:
import json
import os
import pandas as pd
from utils.dcm2niix import *
from utils.selection import *

from datetime import datetime

BERN_PATH='/nasdata/Berner_Daten/Other_Side_Bilddaten'

In [4]:
# for app selection 
DATA_DIR = "/nasdata/Berner_Daten/Other_Side_Bilddaten"  # <------ Path to the RAW data
PROJECT_DIR = "/home/bule/berner_daten_analyse"          # <------ Path to the project directory
DATA_PATH='/home/bule/berner_daten_analyse/data'
APP_DATA_PATH='/home/bule/berner_daten_analyse/apps/app_manual_preselection/selection_adc_3quartal2025'

# finaly used patients
df_selection=pd.read_csv(os.path.join(DATA_PATH,'clinical','baseline_bern_test_impute_10n.csv'))
df_selection.info()

# all selected sequences
df_no_ = pd.read_csv(os.path.join(PROJECT_DIR,'data','dwi_t1_df_merged.csv'))
df_no_
print(len(set(df_no_['Patient_ID'])))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   p_id                     297 non-null    float64
 1   age                      297 non-null    float64
 2   sex                      297 non-null    int64
 3   nihss                    297 non-null    int64
 4   selbststaendig           297 non-null    int64
 5   prehypert                297 non-null    int64
 6   systol                   297 non-null    int64
 7   toast                    297 non-null    int64
 8   mrs                      297 non-null    float64
 9   MED_prestatin            297 non-null    float64
 10  MED_Parenteral           297 non-null    float64
 11  MED_Dabigatran_Pradaxa   297 non-null    float64
 12  MED_Rivaroxaban_Xarelto  297 non-null    float64
 13  MED_Vit_K_ag             297 non-null    float64
 14  MED_Ticagrelor           297 non-null    float64
 15  MED_Clopidogrel          297 non-null    float64
 16  mrs_unfavorable          297 non-null    int64
 17  p_idx                    297 non-null    int64
dtypes: float64(10), int64(8)
memory usage: 41.9 KB
430

In [5]:
df_no_['p_id_float'] = df_no_['Patient_ID'].astype(float)
df_no_subsel=df_no_[df_no_['p_id_float'].isin(df_selection['p_id'].astype(float))]

only_2_df=pd.read_csv('/home/bule/berner_daten_analyse/data/only_2_df.csv')
only_2_df_selection = only_2_df[only_2_df['Patient_ID'].isin(df_selection['p_id'].astype(float))]
only_2_df_selection_dwi= only_2_df_selection[only_2_df_selection['Modality']=='dwi']
# uncomment to save the file for adc selection app
# only_2_df_selection_dwi.merge(df_no_subsel, on=["Patient_ID","Sequence_ID","Study_ID","Modality","Date"], how="left").to_csv(os.path.join(DATA_PATH,"dwi_t1_df_merged_selection_for_adc2.csv", index=False))
only_2_df_selection_dwi

,Patient_ID,Study_ID,Sequence_ID,Full_Path_Nifti,join_crit,Path_Nifti,Modality,Date,Shape
0,76813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/000...,/0000076813/20170614_4361718/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2017-06-14,"(128, 128, 25, 2)"
2,442968,20151109_3835318,ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30...,/home/bule/berner_daten_analyse/data/nifti/000...,/0000442968/20151109_3835318/ep2d_diff_3scan_t...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2015-11-09,"(192, 192, 19, 2)"
4,481858,20121025_3013771,resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12....,/home/bule/berner_daten_analyse/data/nifti/000...,/0000481858/20121025_3013771/resolve_3scan_tra...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2012-10-25,"(176, 176, 20, 2)"
8,653853,20161216_4193466,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/000...,/0000653853/20161216_4193466/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2016-12-16,"(128, 128, 25, 2)"
12,768081,20130110_3061277,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/000...,/0000768081/20130110_3061277/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2013-01-10,"(128, 128, 25, 2)"
...,...,...,...,...,...,...,...,...,...
826,14150158,20170626_4372408,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/001...,/0014150158/20170626_4372408/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/001...,dwi,2017-06-26,"(128, 128, 25, 2)"
832,14239248,20170809_4413689,ep2d_diff_4scan_trace_p2_s2_inkl.Neckcoil_TRAC...,/home/bule/berner_daten_analyse/data/nifti/001...,/0014239248/20170809_4413689/ep2d_diff_4scan_t...,/home/bule/berner_daten_analyse/data/nifti/001...,dwi,2017-08-09,"(384, 384, 30, 2)"
840,82298262,20161224_4200830,ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30...,/home/bule/berner_daten_analyse/data/nifti/008...,/0082298262/20161224_4200830/ep2d_diff_3scan_t...,/home/bule/berner_daten_analyse/data/nifti/008...,dwi,2016-12-24,"(192, 192, 19, 2)"
844,82364672,20170112_4215453,resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12....,/home/bule/berner_daten_analyse/data/nifti/008...,/0082364672/20170112_4215453/resolve_3scan_tra...,/home/bule/berner_daten_analyse/data/nifti/008...,dwi,2017-01-12,"(176, 176, 20, 2)"
846,82395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/008...,/0082395993/20170802_4406866/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/008...,dwi,2017-08-02,"(128, 128, 25, 2)"

## Selection with app (apps/app_manual_preselection/0_1_adc_app.py)

In [6]:
folds_id_tab = pd.read_csv(os.path.join(DATA_PATH,"clinical/10Fold_ids_test.csv"))

## rater3

In [ ]:

file_path =os.path.join(APP_DATA_PATH,"rater3_sequences.json")

with open(file_path, "r") as f:
    selection_rater3_dict = json.load(f)

rows = []
for patid, selection_dict in selection_rater3_dict.items():
    for modality, sequences in selection_dict.items():
        for sequence in sequences:
            study_id, sequence_id = sequence.split('/')
            rows.append({
                'Patient_ID': patid,
                'Study_ID': study_id,
                'Sequence_ID': sequence_id,
                'Modality': modality,
                'Labeller': 'rater3'  
            })
selection_rater3_df = pd.DataFrame(rows).drop_duplicates()
selection_rater3_df['Sequence_path']=selection_rater3_df.apply(lambda x: os.path.join(BERN_PATH,x['Patient_ID'],x['Study_ID'],x['Sequence_ID']),axis=1)
selection_rater3_df['Date'] = selection_rater3_df['Study_ID'].str[:8].apply(lambda x: datetime.strptime(x, '%Y%m%d').strftime('%Y-%m-%d'))

In [ ]:
selection_rater3_df

,Patient_ID,Study_ID,Sequence_ID,Modality,Labeller,Sequence_path,Date
0,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2017-06-14
1,0000442968,20151109_3835318,ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2015-11-09
2,0000481858,20121025_3013771,resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1...,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2012-10-25
3,0000653853,20161216_4193466,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2016-12-16
4,0000801402,20161123_4171427,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2016-11-23
...,...,...,...,...,...,...,...
293,0014150158,20170626_4372408,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/001...,2017-06-26
294,0014239248,20170809_4413689,ep2d_diff_4scan_trace_p2_s2_inkl.Neckcoil_ADC_...,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/001...,2017-08-09
295,0082298262,20161224_4200830,ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,2016-12-24
296,0082364672,20170112_4215453,resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1...,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,2017-01-12
297,0082395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,2017-08-02

In [ ]:
selection_rater3_df["pi_d_float"] = selection_rater3_df["Patient_ID"].astype(float)
pids_missing = folds_id_tab.loc[~folds_id_tab["p_id"].isin(selection_rater3_df["pi_d_float"]), "p_id"]
pids_missing

Series([], Name: p_id, dtype: float64)

In [ ]:
mask = selection_rater3_df['Sequence_ID'].str.lower().str.contains("neckcoil|neck|coil")

inds = selection_rater3_df.index[mask]
inds

Index([294], dtype='int64')

In [ ]:
selection_rater3_df.iloc[294]

Patient_ID                                              0082298262
Study_ID                                          20161224_4200830
Sequence_ID      ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5....
Modality                                                     other
Labeller                                                    Martin
Sequence_path    /nasdata/Berner_Daten/Other_Side_Bilddaten/008...
Date                                                    2016-12-24
pi_d_float                                              82298262.0
Name: 295, dtype: object

## rater1

## Merge

In [ ]:
merge_selection=selection_rater3_df

In [13]:
merge_selection

,Patient_ID,Study_ID,Sequence_ID,Modality,Labeller,Sequence_path,Date,pi_d_float
0,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2017-06-14,76813.0
1,0000442968,20151109_3835318,ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2015-11-09,442968.0
2,0000481858,20121025_3013771,resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1...,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2012-10-25,481858.0
3,0000653853,20161216_4193466,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2016-12-16,653853.0
4,0000801402,20161123_4171427,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2016-11-23,801402.0
...,...,...,...,...,...,...,...,...
293,0014150158,20170626_4372408,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/001...,2017-06-26,14150158.0
294,0014239248,20170809_4413689,ep2d_diff_4scan_trace_p2_s2_inkl.Neckcoil_ADC_...,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/001...,2017-08-09,14239248.0
295,0082298262,20161224_4200830,ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,2016-12-24,82298262.0
296,0082364672,20170112_4215453,resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1...,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,2017-01-12,82364672.0
297,0082395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,2017-08-02,82395993.0

## converzt to nifti

In [14]:
adc_df = []  # 
for _, row in merge_selection.iterrows():
    for dcm_ending in os.listdir(row['Sequence_path']):        
        adc_df.append({
            'Patient_ID': row['Patient_ID'],
            'Study_ID': row['Study_ID'],
            'Sequence_ID': row['Sequence_ID'],
            'File_Name': dcm_ending,
            'Full_Path': os.path.join(row['Sequence_path'], dcm_ending),
            'Modality': row['Modality'].upper()
        })

adc_df = pd.DataFrame(adc_df)
adc_df['Date'] = adc_df['Study_ID'].str[:8].apply(lambda x: datetime.strptime(x, '%Y%m%d').strftime('%Y-%m-%d'))
adc_df['Sequence_ID_split'] = adc_df['Sequence_ID'].apply(lambda x: split_at_anynumber_seq(x))

adc_df["File_Number"] = adc_df["File_Name"].str.extract(r'(\d+)').astype(int)
adc_df.sort_values(["Patient_ID", "Modality", "File_Number"], inplace=True)
adc_df.drop(columns=["File_Number"], inplace=True)
adc_df.reset_index()
# adc_df.to_csv(os.path.join(DATA_PATH, 'adc_df.csv'), index=False)

,index,Patient_ID,Study_ID,Sequence_ID,File_Name,Full_Path,Modality,Date,Sequence_ID_split
0,0,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,1.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,OTHER,2017-06-14,ep2d_diff_M128_b0_1000_DIN_ADC
1,11,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,2.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,OTHER,2017-06-14,ep2d_diff_M128_b0_1000_DIN_ADC
2,18,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,3.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,OTHER,2017-06-14,ep2d_diff_M128_b0_1000_DIN_ADC
3,19,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,4.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,OTHER,2017-06-14,ep2d_diff_M128_b0_1000_DIN_ADC
4,20,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,5.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,OTHER,2017-06-14,ep2d_diff_M128_b0_1000_DIN_ADC
...,...,...,...,...,...,...,...,...,...
6370,6363,0082395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,21.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,OTHER,2017-08-02,ep2d_diff_M128_b0_1000_DIN_ADC
6371,6364,0082395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,22.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,OTHER,2017-08-02,ep2d_diff_M128_b0_1000_DIN_ADC
6372,6365,0082395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,23.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,OTHER,2017-08-02,ep2d_diff_M128_b0_1000_DIN_ADC
6373,6366,0082395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,24.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,OTHER,2017-08-02,ep2d_diff_M128_b0_1000_DIN_ADC
6374,6367,0082395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,25.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,OTHER,2017-08-02,ep2d_diff_M128_b0_1000_DIN_ADC

In [15]:
# Project data path
DATA_PATH='/home/bule/berner_daten_analyse/data'
NII_TARGET_PATH = '/home/bule/berner_daten_analyse/data/nifti'
LOG_PATH = os.path.join(NII_TARGET_PATH, 'conversion_errors_selection.log')

adc_df.sort_values(by='Patient_ID',inplace=True)
adc_df.head()
print(len(adc_df))

adc_df.groupby('Patient_ID').nunique().head()

6375

,Study_ID,Sequence_ID,File_Name,Full_Path,Modality,Date,Sequence_ID_split
Patient_ID,,,,,,,
0000076813,1,1,25,25,1,1,1
0000442968,1,1,19,19,1,1,1
0000481858,1,1,20,20,1,1,1
0000653853,1,1,25,25,1,1,1
0000768081,1,1,25,25,1,1,1

In [16]:
adc_df

,Patient_ID,Study_ID,Sequence_ID,File_Name,Full_Path,Modality,Date,Sequence_ID_split
0,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,1.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,OTHER,2017-06-14,ep2d_diff_M128_b0_1000_DIN_ADC
17,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,25.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,OTHER,2017-06-14,ep2d_diff_M128_b0_1000_DIN_ADC
16,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,24.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,OTHER,2017-06-14,ep2d_diff_M128_b0_1000_DIN_ADC
15,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,23.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,OTHER,2017-06-14,ep2d_diff_M128_b0_1000_DIN_ADC
14,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,22.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,OTHER,2017-06-14,ep2d_diff_M128_b0_1000_DIN_ADC
...,...,...,...,...,...,...,...,...
6361,0082395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,2.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,OTHER,2017-08-02,ep2d_diff_M128_b0_1000_DIN_ADC
6350,0082395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,1.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,OTHER,2017-08-02,ep2d_diff_M128_b0_1000_DIN_ADC
6366,0082395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,24.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,OTHER,2017-08-02,ep2d_diff_M128_b0_1000_DIN_ADC
6353,0082395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,12.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,OTHER,2017-08-02,ep2d_diff_M128_b0_1000_DIN_ADC
6367,0082395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,25.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,OTHER,2017-08-02,ep2d_diff_M128_b0_1000_DIN_ADC

In [17]:
adc_df = adc_df[adc_df['Modality']=='OTHER']
source_dcm_sequences = [os.path.join('/',*path.split('/')[:-1]) for path in adc_df['Full_Path']]
source_dcm_sequences = list(set([os.path.join('/',path) for path in source_dcm_sequences]))
print(source_dcm_sequences[0])
target_nii_sequences= [os.path.join(*path.split('/')[4:]) for path in source_dcm_sequences]
target_nii_sequences_adc= [os.path.join(NII_TARGET_PATH,path) for path in target_nii_sequences]
print(target_nii_sequences_adc[0])

/nasdata/Berner_Daten/Other_Side_Bilddaten/0009157646/20131022_3257263/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013102220135264655603624.0.0.0
/home/bule/berner_daten_analyse/data/nifti/0009157646/20131022_3257263/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013102220135264655603624.0.0.0

In [18]:
df_modality = pd.DataFrame({
    'Path_Nifti': target_nii_sequences_adc,
    'Modality': ['adc'] * len(target_nii_sequences_adc),
})
df_modality['join_crit']=[ os.path.join('/',*path.split('/')[6:]) for path in df_modality['Path_Nifti']] # just  to get the modality
df_modality

,Path_Nifti,Modality,join_crit
0,/home/bule/berner_daten_analyse/data/nifti/000...,adc,/0009157646/20131022_3257263/ep2d_diff_3scan_t...
1,/home/bule/berner_daten_analyse/data/nifti/000...,adc,/0001029355/20150421_3667803/ep2d_diff_3scan_t...
2,/home/bule/berner_daten_analyse/data/nifti/000...,adc,/0003410390/20170418_4309773/ep2d_diff_tra_res...
3,/home/bule/berner_daten_analyse/data/nifti/001...,adc,/0013361457/20160427_3981418/ep2d_diff_3scan_t...
4,/home/bule/berner_daten_analyse/data/nifti/001...,adc,/0013341421/20160417_3971699/ep2d_diff_M128_b0...
...,...,...,...
292,/home/bule/berner_daten_analyse/data/nifti/008...,adc,/0082395993/20170802_4406866/ep2d_diff_M128_b0...
293,/home/bule/berner_daten_analyse/data/nifti/000...,adc,/0001357840/20170130_4232882/ep2d_diff_M128_b0...
294,/home/bule/berner_daten_analyse/data/nifti/000...,adc,/0004117115/20170401_4293389/ep2d_diff_3scan_t...
295,/home/bule/berner_daten_analyse/data/nifti/000...,adc,/0005771439/20160523_4003187/ep2d_diff_3scan_t...
296,/home/bule/berner_daten_analyse/data/nifti/001...,adc,/0013273060/20160310_3938991/resolve_3scan_tra...

In [19]:
process_niftis=False
if process_niftis:
    process_directories(source_dcm_sequences, target_nii_sequences,log_path=LOG_PATH)# ~ 11 mins

## prepare df for lesion segmentation

-create file with the realized nifticonverison like th only_2 df

    - check target sequenzes with realiezed sequences

In [20]:
succesfull_adc_niftis=[]
for dir_ in target_nii_sequences_adc:
    file_count=0
    if not os.path.exists(dir_):
        print(f"Directory {directory} does not exist.")
    
    for file in os.listdir(dir_):
        if file.startswith('b1000-extracted-'):
                continue
        if file.endswith('.nii') or file.endswith('.nii.gz'):
            succesfull_adc_niftis.append(os.path.join(dir_,file))

len(set(succesfull_adc_niftis))

297

In [21]:
succesfull_adc_niftis

['/home/bule/berner_daten_analyse/data/nifti/0009157646/20131022_3257263/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013102220135264655603624.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2013102220135264655603624.0.0.0_ep2d_diff_3scan_trace_p2_20131022201218_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0001029355/20150421_3667803/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015042113370162060649641.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015042113370162060649641.0.0.0_ep2d_diff_3scan_trace_p2_20150421133546_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0003410390/20170418_4309773/ep2d_diff_tra_resolve_ADC__1.3.12.2.1107.5.2.18.41102.2017041807294828614202566.0.0.0/ep2d_diff_tra_resolve_ADC_1.3.12.2.1107.5.2.18.41102.2017041807294828614202566.0.0.0_ep2d_diff_tra_resolve_20170418071959_8.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0013361457/20160427_3981418/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016042712312612374340705.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016042712312612374340705.0.0.0_ep2d_diff_3scan_trace_p2_20160427122854_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0013341421/20160417_3971699/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016041713384993450322446.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2016041713384993450322446.0.0.0_ep2d_diff_M128_b0_1000_DIN_20160417133658_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0011069368/20120629_2939441/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012062920264377595808813.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2012062920264377595808813.0.0.0_ep2d_diff_3scan_trace_p2_20120629202348_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0013105663/20151208_3860103/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2015120819281435262084705.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2015120819281435262084705.0.0.0_ep2d_diff_M128_b0_1000_DIN_20151208192622_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0007815360/20140614_3430160/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2014061410232886392209257.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2014061410232886392209257.0.0.0_ep2d_diff_3scan_trace_p2_20140614102146_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0013904620/20170220_4253696/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017022019533284029464194.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2017022019533284029464194.0.0.0_ep2d_diff_3scan_trace_p2_20170220195048_4.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0011737328/20130818_3211640/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013081806581426018001342.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2013081806581426018001342.0.0.0_ep2d_diff_3scan_trace_p2_20130818065620_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0013213261/20160210_3912721/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016021006173840652039151.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016021006173840652039151.0.0.0_ep2d_diff_3scan_trace_p2_20160210061515_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0012524182/20150112_3587862/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015011215404114490871420.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015011215404114490871420.0.0.0_ep2d_diff_3scan_trace_p2_20150112153840_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0013726250/20161115_4163094/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016111513570850700958667.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016111513570850700958667.0.0.0_ep2d_diff_3scan_trace_p2_20161115135255_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0010957448/20120428_2900621/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.201204280936576983508645.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.201204280936576983508645.0.0.0_ep2d_diff_3scan_trace_p2_20120428093502_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0005768640/20150416_3663784/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015041607244246524101339.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015041607244246524101339.0.0.0_ep2d_diff_3scan_trace_p2_20150416072316_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0004751884/20160825_4085988/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016082505265456580980765.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016082505265456580980765.0.0.0_ep2d_diff_3scan_trace_p2_20160825052535_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0013806831/20161231_4205208/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016123103171570886101345.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016123103171570886101345.0.0.0_ep2d_diff_3scan_trace_p2_20161231031314_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0013561340/20160814_4075674/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016081423232347130234856.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016081423232347130234856.0.0.0_ep2d_diff_3scan_trace_p2_20160814232122_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0000911666/20170318_4279828/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017031803434419578756163.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2017031803434419578756163.0.0.0_ep2d_diff_3scan_trace_p2_20170318034215_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0011420316/20130204_3078550/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2013020411064122454430395.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2013020411064122454430395.0.0.0_ep2d_diff_M128_b0_1000_DIN_20130204110226_4.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0008505020/20161024_4142199/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.201610241554179766291780.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40186.201610241554179766291780.0.0.0_ep2d_diff_M128_b0_1000_DIN_20161024155220_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0012752479/20150509_3683394/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015050911245686910728617.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015050911245686910728617.0.0.0_ep2d_diff_3scan_trace_p2_20150509112322_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0013982095/20170401_4293517/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017040120033418406712910.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2017040120033418406712910.0.0.0_ep2d_diff_3scan_trace_p2_20170401200209_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0001728245/20160602_4011937/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2016060213155013546642903.0.0.0/resolve_3scan_trace_tra_176_p2_ADC_1.3.12.2.1107.5.2.18.41437.2016060213155013546642903.0.0.0_resolve_3scan_trace_tra_176_p2_20160602131359_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0007956525/20121210_3044374/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2012121017501123667780863.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2012121017501123667780863.0.0.0_ep2d_diff_M128_b0_1000_DIN_20121210174825_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0012580430/20150124_3598121/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015012411411240581387359.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015012411411240581387359.0.0.0_ep2d_diff_3scan_trace_p2_20150124113949_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0002923041/20170703_4379063/Diffusion_tra_3mm_ADC__1.3.12.2.1107.5.2.18.141120.2017070310463983789143341.0.0.0/Diffusion_tra_3mm_ADC_1.3.12.2.1107.5.2.18.141120.2017070310463983789143341.0.0.0_Diffusion_tra_3mm_20170703104502_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0007803001/20130605_3160831/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013060518553430651457279.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2013060518553430651457279.0.0.0_ep2d_diff_3scan_trace_p2_20130605185301_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0001305751/20160423_3978120/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016042317505420514655212.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016042317505420514655212.0.0.0_ep2d_diff_3scan_trace_p2_20160423174841_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0010721312/20151028_3825190/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015102812275277228458082.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015102812275277228458082.0.0.0_ep2d_diff_3scan_trace_p2_20151028122457_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0013250558/20160301_3930264/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016030116515490319838509.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2016030116515490319838509.0.0.0_ep2d_diff_M128_b0_1000_DIN_20160301164038_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0001120794/20170116_4218415/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017011615131252371173003.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2017011615131252371173003.0.0.0_ep2d_diff_3scan_trace_p2_20170116151147_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0010997857/20120523_2915739/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2012052309145187437608354.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2012052309145187437608354.0.0.0_ep2d_diff_M128_b0_1000_DIN_20120523091246_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0008436487/20170612_4358040/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2017061213340585324746682.0.0.0/resolve_3scan_trace_tra_176_p2_ADC_1.3.12.2.1107.5.2.18.41437.2017061213340585324746682.0.0.0_resolve_3scan_trace_tra_176_p2_20170612133232_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0012781541/20150526_3696011/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2015052615191539489540002.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2015052615191539489540002.0.0.0_ep2d_diff_M128_b0_1000_DIN_20150526151714_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0000481858/20121025_3013771/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2012102507535097175206178.0.0.0/resolve_3scan_trace_tra_176_p2_ADC_1.3.12.2.1107.5.2.18.41437.2012102507535097175206178.0.0.0_resolve_3scan_trace_tra_176_p2_20121025075220_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0011293764/20130708_3183238/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013070810395476199318553.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2013070810395476199318553.0.0.0_ep2d_diff_3scan_trace_p2_20130708103814_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0012870480/20150715_3739282/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2015071517302852321687772.0.0.0/resolve_3scan_trace_tra_176_p2_ADC_1.3.12.2.1107.5.2.18.41437.2015071517302852321687772.0.0.0_resolve_3scan_trace_tra_176_p2_20150715172801_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0013164171/20160114_3888741/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.2016011408422394680007345.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40186.2016011408422394680007345.0.0.0_ep2d_diff_M128_b0_1000_DIN_20160114084021_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0082364672/20170112_4215453/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2017011211103382964145931.0.0.0/resolve_3scan_trace_tra_176_p2_ADC_1.3.12.2.1107.5.2.18.41437.2017011211103382964145931.0.0.0_resolve_3scan_trace_tra_176_p2_20170112110900_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0000442968/20151109_3835318/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015110920165992102092193.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015110920165992102092193.0.0.0_ep2d_diff_3scan_trace_p2_20151109201528_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0013017152/20151017_3816432/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015101723393844339265263.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015101723393844339265263.0.0.0_ep2d_diff_3scan_trace_p2_20151017233745_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0000830267/20140331_3374880/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.20140331175722548233096.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.20140331175722548233096.0.0.0_ep2d_diff_M128_b0_1000_DIN_20140331175529_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0004905113/20150501_3677174/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015050113384736814330990.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015050113384736814330990.0.0.0_ep2d_diff_3scan_trace_p2_20150501133729_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0011357428/20121222_3052849/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2012122213291045397701374.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2012122213291045397701374.0.0.0_ep2d_diff_M128_b0_1000_DIN_20121222132715_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0003938921/20141229_3578338/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2014122912054939880982670.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2014122912054939880982670.0.0.0_ep2d_diff_M128_b0_1000_DIN_20141229120415_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0012873870/20150717_3741110/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.2015071714094897961545459.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40186.2015071714094897961545459.0.0.0_ep2d_diff_M128_b0_1000_DIN_20150717140436_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0013184407/20160127_3900057/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016012709384890487917933.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2016012709384890487917933.0.0.0_ep2d_diff_M128_b0_1000_DIN_20160127093703_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0004769619/20160325_3952357/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016032507024493479801339.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016032507024493479801339.0.0.0_ep2d_diff_3scan_trace_p2_20160325065931_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0013915045/20170226_4259441/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017022622555492999245605.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2017022622555492999245605.0.0.0_ep2d_diff_3scan_trace_p2_20170226225440_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0000653853/20161216_4193466/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.2016121611003455620544484.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40186.2016121611003455620544484.0.0.0_ep2d_diff_M128_b0_1000_DIN_20161216105853_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0014068680/20170513_4332471/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017051320154750507188361.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2017051320154750507188361.0.0.0_ep2d_diff_3scan_trace_p2_20170513201435_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0013102567/20151207_3858717/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015120716380771820078357.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015120716380771820078357.0.0.0_ep2d_diff_3scan_trace_p2_20151207163627_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0007695411/20160805_4068774/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.2016080515275022512276773.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40186.2016080515275022512276773.0.0.0_ep2d_diff_M128_b0_1000_DIN_20160805152555_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0006593860/20131113_3272791/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.201311131037005125732859.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.201311131037005125732859.0.0.0_ep2d_diff_M128_b0_1000_DIN_20131113102010_10.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0000876763/20120405_2888249/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2012040521123029117644434.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2012040521123029117644434.0.0.0_ep2d_diff_M128_b0_1000_DIN_20120405204237_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0007341989/20140116_3316435/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2014011606573737868801341.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2014011606573737868801341.0.0.0_ep2d_diff_3scan_trace_p2_20140116065104_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0011002875/20141030_3532083/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2014103007575436634517314.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2014103007575436634517314.0.0.0_ep2d_diff_3scan_trace_p2_20141030075621_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0013571265/20160820_4081400/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016082009093337864233519.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016082009093337864233519.0.0.0_ep2d_diff_3scan_trace_p2_20160820090721_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0003049183/20161016_4134204/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016101614255073295125811.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2016101614255073295125811.0.0.0_ep2d_diff_M128_b0_1000_DIN_20161016142338_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0006582044/20150928_3799841/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015092809421553081953265.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015092809421553081953265.0.0.0_ep2d_diff_3scan_trace_p2_20150928094044_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0013635859/20160926_4116146/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.2016092614372271150568867.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40186.2016092614372271150568867.0.0.0_ep2d_diff_M128_b0_1000_DIN_20160926143511_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0013230824/20160218_3920209/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016021810564642021054110.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016021810564642021054110.0.0.0_ep2d_diff_3scan_trace_p2_20160218105521_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0004524152/20150815_3764238/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015081513043289756871481.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015081513043289756871481.0.0.0_ep2d_diff_3scan_trace_p2_20150815130256_3.nii.gz',
 '/home/bule/berner_daten_analyse/data/nifti/0001428012/20160927_4117379/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2016092715122564973749282.0.0.0/resolve_3scan_trace_tra_176_p2_ADC_1.3.12.2.1107.5.2.18.41437.2016092715122564973749282.0.0.0_resolve_3scan_trace_tra_176_p2_20160927151038_3.nii.gz',

In [22]:
data=[]
for path in succesfull_adc_niftis:
    patient_id = int(path.split("/")[6])
    study_id = path.split("/")[7]
    sequence_id = path.split("/")[8]
    full_path = path
    data.append({'Patient_ID':patient_id, 'Study_ID':study_id,'Sequence_ID':sequence_id ,'Full_Path_Nifti':full_path})
    
nii_df=pd.DataFrame(data)

nii_df['join_crit']=[ os.path.join('/',*path.split('/')[6:-1]) for path in nii_df['Full_Path_Nifti']]
nii_df=nii_df.merge(df_modality, on='join_crit', how='left')

# len(nii_df[['Sequence_ID','Study_ID']].unique()) 
duplicates = nii_df[nii_df.duplicated(subset=['Study_ID', 'Sequence_ID'], keep=False)]
print(duplicates.head(1))

nii_df.drop_duplicates(subset=['Sequence_ID'], keep='first', inplace=True)
nii_df.info()

Empty DataFrame
Columns: [Patient_ID, Study_ID, Sequence_ID, Full_Path_Nifti, join_crit, Path_Nifti, Modality]
Index: []
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Patient_ID       297 non-null    int64
 1   Study_ID         297 non-null    object
 2   Sequence_ID      297 non-null    object
 3   Full_Path_Nifti  297 non-null    object
 4   join_crit        297 non-null    object
 5   Path_Nifti       297 non-null    object
 6   Modality         297 non-null    object
dtypes: int64(1), object(6)
memory usage: 16.4+ KB

In [23]:
nii_df

,Patient_ID,Study_ID,Sequence_ID,Full_Path_Nifti,join_crit,Path_Nifti,Modality
0,9157646,20131022_3257263,ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5....,/home/bule/berner_daten_analyse/data/nifti/000...,/0009157646/20131022_3257263/ep2d_diff_3scan_t...,/home/bule/berner_daten_analyse/data/nifti/000...,adc
1,1029355,20150421_3667803,ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5....,/home/bule/berner_daten_analyse/data/nifti/000...,/0001029355/20150421_3667803/ep2d_diff_3scan_t...,/home/bule/berner_daten_analyse/data/nifti/000...,adc
2,3410390,20170418_4309773,ep2d_diff_tra_resolve_ADC__1.3.12.2.1107.5.2.1...,/home/bule/berner_daten_analyse/data/nifti/000...,/0003410390/20170418_4309773/ep2d_diff_tra_res...,/home/bule/berner_daten_analyse/data/nifti/000...,adc
3,13361457,20160427_3981418,ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5....,/home/bule/berner_daten_analyse/data/nifti/001...,/0013361457/20160427_3981418/ep2d_diff_3scan_t...,/home/bule/berner_daten_analyse/data/nifti/001...,adc
4,13341421,20160417_3971699,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,/home/bule/berner_daten_analyse/data/nifti/001...,/0013341421/20160417_3971699/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/001...,adc
...,...,...,...,...,...,...,...
292,82395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,/home/bule/berner_daten_analyse/data/nifti/008...,/0082395993/20170802_4406866/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/008...,adc
293,1357840,20170130_4232882,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,/home/bule/berner_daten_analyse/data/nifti/000...,/0001357840/20170130_4232882/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/000...,adc
294,4117115,20170401_4293389,ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5....,/home/bule/berner_daten_analyse/data/nifti/000...,/0004117115/20170401_4293389/ep2d_diff_3scan_t...,/home/bule/berner_daten_analyse/data/nifti/000...,adc
295,5771439,20160523_4003187,ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5....,/home/bule/berner_daten_analyse/data/nifti/000...,/0005771439/20160523_4003187/ep2d_diff_3scan_t...,/home/bule/berner_daten_analyse/data/nifti/000...,adc
296,13273060,20160310_3938991,resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1...,/home/bule/berner_daten_analyse/data/nifti/001...,/0013273060/20160310_3938991/resolve_3scan_tra...,/home/bule/berner_daten_analyse/data/nifti/001...,adc

## merge dwi sel and adc sel

merge the 2 such that there are for each patients an adc and dwi nii file

In [24]:
# check all 297 patients are represented in nii df
only_2_df_selection_dwi[only_2_df_selection_dwi['Patient_ID'].isin(nii_df['Patient_ID'].astype(float))]

,Patient_ID,Study_ID,Sequence_ID,Full_Path_Nifti,join_crit,Path_Nifti,Modality,Date,Shape
0,76813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/000...,/0000076813/20170614_4361718/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2017-06-14,"(128, 128, 25, 2)"
2,442968,20151109_3835318,ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30...,/home/bule/berner_daten_analyse/data/nifti/000...,/0000442968/20151109_3835318/ep2d_diff_3scan_t...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2015-11-09,"(192, 192, 19, 2)"
4,481858,20121025_3013771,resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12....,/home/bule/berner_daten_analyse/data/nifti/000...,/0000481858/20121025_3013771/resolve_3scan_tra...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2012-10-25,"(176, 176, 20, 2)"
8,653853,20161216_4193466,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/000...,/0000653853/20161216_4193466/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2016-12-16,"(128, 128, 25, 2)"
12,768081,20130110_3061277,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/000...,/0000768081/20130110_3061277/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2013-01-10,"(128, 128, 25, 2)"
...,...,...,...,...,...,...,...,...,...
826,14150158,20170626_4372408,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/001...,/0014150158/20170626_4372408/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/001...,dwi,2017-06-26,"(128, 128, 25, 2)"
832,14239248,20170809_4413689,ep2d_diff_4scan_trace_p2_s2_inkl.Neckcoil_TRAC...,/home/bule/berner_daten_analyse/data/nifti/001...,/0014239248/20170809_4413689/ep2d_diff_4scan_t...,/home/bule/berner_daten_analyse/data/nifti/001...,dwi,2017-08-09,"(384, 384, 30, 2)"
840,82298262,20161224_4200830,ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30...,/home/bule/berner_daten_analyse/data/nifti/008...,/0082298262/20161224_4200830/ep2d_diff_3scan_t...,/home/bule/berner_daten_analyse/data/nifti/008...,dwi,2016-12-24,"(192, 192, 19, 2)"
844,82364672,20170112_4215453,resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12....,/home/bule/berner_daten_analyse/data/nifti/008...,/0082364672/20170112_4215453/resolve_3scan_tra...,/home/bule/berner_daten_analyse/data/nifti/008...,dwi,2017-01-12,"(176, 176, 20, 2)"
846,82395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/008...,/0082395993/20170802_4406866/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/008...,dwi,2017-08-02,"(128, 128, 25, 2)"

In [25]:
only_2_df_selection_dwi

,Patient_ID,Study_ID,Sequence_ID,Full_Path_Nifti,join_crit,Path_Nifti,Modality,Date,Shape
0,76813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/000...,/0000076813/20170614_4361718/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2017-06-14,"(128, 128, 25, 2)"
2,442968,20151109_3835318,ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30...,/home/bule/berner_daten_analyse/data/nifti/000...,/0000442968/20151109_3835318/ep2d_diff_3scan_t...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2015-11-09,"(192, 192, 19, 2)"
4,481858,20121025_3013771,resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12....,/home/bule/berner_daten_analyse/data/nifti/000...,/0000481858/20121025_3013771/resolve_3scan_tra...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2012-10-25,"(176, 176, 20, 2)"
8,653853,20161216_4193466,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/000...,/0000653853/20161216_4193466/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2016-12-16,"(128, 128, 25, 2)"
12,768081,20130110_3061277,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/000...,/0000768081/20130110_3061277/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2013-01-10,"(128, 128, 25, 2)"
...,...,...,...,...,...,...,...,...,...
826,14150158,20170626_4372408,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/001...,/0014150158/20170626_4372408/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/001...,dwi,2017-06-26,"(128, 128, 25, 2)"
832,14239248,20170809_4413689,ep2d_diff_4scan_trace_p2_s2_inkl.Neckcoil_TRAC...,/home/bule/berner_daten_analyse/data/nifti/001...,/0014239248/20170809_4413689/ep2d_diff_4scan_t...,/home/bule/berner_daten_analyse/data/nifti/001...,dwi,2017-08-09,"(384, 384, 30, 2)"
840,82298262,20161224_4200830,ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30...,/home/bule/berner_daten_analyse/data/nifti/008...,/0082298262/20161224_4200830/ep2d_diff_3scan_t...,/home/bule/berner_daten_analyse/data/nifti/008...,dwi,2016-12-24,"(192, 192, 19, 2)"
844,82364672,20170112_4215453,resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12....,/home/bule/berner_daten_analyse/data/nifti/008...,/0082364672/20170112_4215453/resolve_3scan_tra...,/home/bule/berner_daten_analyse/data/nifti/008...,dwi,2017-01-12,"(176, 176, 20, 2)"
846,82395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/008...,/0082395993/20170802_4406866/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/008...,dwi,2017-08-02,"(128, 128, 25, 2)"

In [ ]:

###################### ADJSUT THE FILES HERE
ANALYSIS_PATH='/home/bule/berner_daten_analyse/data'
NII_TARGET_PATH ='/home/bule/berner_daten_analyse/data/nifti_third_try' #'/home/bule/berner_daten_analyse/data/nifti_second_try'
df_only_2=pd.read_csv(os.path.join(ANALYSIS_PATH, 'only_2_df.csv'))# each patietn has 2 nfitis

In [27]:
df_only_3=pd.concat([nii_df,df_only_2])

In [37]:
df_only_3

,Patient_ID,Study_ID,Sequence_ID,Full_Path_Nifti,join_crit,Path_Nifti,Modality,Date,Shape
0,9157646,20131022_3257263,ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5....,/home/bule/berner_daten_analyse/data/nifti/000...,/0009157646/20131022_3257263/ep2d_diff_3scan_t...,/home/bule/berner_daten_analyse/data/nifti/000...,adc,NaN,NaN
1,1029355,20150421_3667803,ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5....,/home/bule/berner_daten_analyse/data/nifti/000...,/0001029355/20150421_3667803/ep2d_diff_3scan_t...,/home/bule/berner_daten_analyse/data/nifti/000...,adc,NaN,NaN
2,3410390,20170418_4309773,ep2d_diff_tra_resolve_ADC__1.3.12.2.1107.5.2.1...,/home/bule/berner_daten_analyse/data/nifti/000...,/0003410390/20170418_4309773/ep2d_diff_tra_res...,/home/bule/berner_daten_analyse/data/nifti/000...,adc,NaN,NaN
3,13361457,20160427_3981418,ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5....,/home/bule/berner_daten_analyse/data/nifti/001...,/0013361457/20160427_3981418/ep2d_diff_3scan_t...,/home/bule/berner_daten_analyse/data/nifti/001...,adc,NaN,NaN
4,13341421,20160417_3971699,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,/home/bule/berner_daten_analyse/data/nifti/001...,/0013341421/20160417_3971699/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/001...,adc,NaN,NaN
...,...,...,...,...,...,...,...,...,...
845,82364672,20170113_4216439,t1_fl2d_tra__1.3.12.2.1107.5.2.36.40186.201701...,/home/bule/berner_daten_analyse/data/nifti/008...,/0082364672/20170113_4216439/t1_fl2d_tra__1.3....,/home/bule/berner_daten_analyse/data/nifti/008...,anatomic,2017-01-13,"(336, 384, 24)"
846,82395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/008...,/0082395993/20170802_4406866/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/008...,dwi,2017-08-02,"(128, 128, 25, 2)"
847,82395993,20170802_4406866,t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.201708...,/home/bule/berner_daten_analyse/data/nifti/008...,/0082395993/20170802_4406866/t1_fl2d_tra__1.3....,/home/bule/berner_daten_analyse/data/nifti/008...,anatomic,2017-08-02,"(324, 384, 24)"
848,82789223,20161003_4120929,resolve_3scan_trace_tra_p3_160_TRACEW__1.3.12....,/home/bule/berner_daten_analyse/data/nifti/008...,/0082789223/20161003_4120929/resolve_3scan_tra...,/home/bule/berner_daten_analyse/data/nifti/008...,dwi,2016-10-03,"(160, 160, 30, 2)"
849,82789223,20160521_4001514,t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.201...,/home/bule/berner_daten_analyse/data/nifti/008...,/0082789223/20160521_4001514/t1_se_r_tra_KM__1...,/home/bule/berner_daten_analyse/data/nifti/008...,anatomic,2016-05-21,"(224, 256, 24)"

In [38]:
import pandas as pd
import os
import nibabel as nib
import numpy as np
import matplotlib.pyplot as plt

from pathlib import Path
from brainles_preprocessing.modality import Modality, CenterModality
from brainles_preprocessing.normalization.percentile_normalizer import (
    PercentileNormalizer,
)
from brainles_preprocessing.preprocessor import Preprocessor




# THE SHAPE OF THE IMAGES SHOULD BE 3 
filter_index_pos = 3

#### extract b1000 sequence assuming that the last sequence is the b1000 sequence
dfnew = df_only_3.copy()
dfnew['sel_b1000']=dfnew['Full_Path_Nifti']


for idx,path in df_only_3['Full_Path_Nifti'].items():
    dwi = nib.load(path)
    dwi_shape = dwi.get_fdata().shape

    if not len(dwi_shape) == filter_index_pos + 1:
        print(f"image of patient {path} does not contain {filter_index_pos + 1} dimensions but has shape {dwi_shape}. Skipping this one.")
        continue

    # Take the last sequence and create a new nifti
    b1000_sequence = dwi.get_fdata()[:, :, :, -1]
    new_nifti = nib.Nifti1Image(b1000_sequence, dwi.affine, dwi.header)

    # save the nifti, prepend the potential b1000 sequence
    nifti_folder_path, dwi_file_name = os.path.split(path)

    new_file_path = os.path.join(nifti_folder_path, "b1000-extracted-" + dwi_file_name)
    
    if os.path.exists(new_file_path):
        print(f"File {new_file_path} already exists. Skipping this one.")
        continue
        
    nib.save(new_nifti, new_file_path)
    
    dfnew.loc[idx,'sel_b1000'] = new_file_path
    
########## create new dataframe with the new paths

dict_paths = {}
for index, row in dfnew.iterrows():
    patient_id = row['Patient_ID']
    if patient_id not in dict_paths:
        dict_paths[patient_id] = {}
    dict_paths[patient_id][row['Modality']] = row['sel_b1000']
dict_paths

image of patient /home/bule/berner_daten_analyse/data/nifti/0009157646/20131022_3257263/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013102220135264655603624.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2013102220135264655603624.0.0.0_ep2d_diff_3scan_trace_p2_20131022201218_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0001029355/20150421_3667803/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015042113370162060649641.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015042113370162060649641.0.0.0_ep2d_diff_3scan_trace_p2_20150421133546_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0003410390/20170418_4309773/ep2d_diff_tra_resolve_ADC__1.3.12.2.1107.5.2.18.41102.2017041807294828614202566.0.0.0/ep2d_diff_tra_resolve_ADC_1.3.12.2.1107.5.2.18.41102.2017041807294828614202566.0.0.0_ep2d_diff_tra_resolve_20170418071959_8.nii.gz does not contain 4 dimensions but has shape (160, 160, 30). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0013361457/20160427_3981418/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016042712312612374340705.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016042712312612374340705.0.0.0_ep2d_diff_3scan_trace_p2_20160427122854_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0013341421/20160417_3971699/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016041713384993450322446.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2016041713384993450322446.0.0.0_ep2d_diff_M128_b0_1000_DIN_20160417133658_3.nii.gz does not contain 4 dimensions but has shape (128, 128, 25). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0011069368/20120629_2939441/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012062920264377595808813.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2012062920264377595808813.0.0.0_ep2d_diff_3scan_trace_p2_20120629202348_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0013105663/20151208_3860103/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2015120819281435262084705.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2015120819281435262084705.0.0.0_ep2d_diff_M128_b0_1000_DIN_20151208192622_3.nii.gz does not contain 4 dimensions but has shape (128, 128, 25). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0007815360/20140614_3430160/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2014061410232886392209257.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2014061410232886392209257.0.0.0_ep2d_diff_3scan_trace_p2_20140614102146_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0013904620/20170220_4253696/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017022019533284029464194.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2017022019533284029464194.0.0.0_ep2d_diff_3scan_trace_p2_20170220195048_4.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0011737328/20130818_3211640/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013081806581426018001342.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2013081806581426018001342.0.0.0_ep2d_diff_3scan_trace_p2_20130818065620_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 23). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0013213261/20160210_3912721/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016021006173840652039151.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016021006173840652039151.0.0.0_ep2d_diff_3scan_trace_p2_20160210061515_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 21). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0012524182/20150112_3587862/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015011215404114490871420.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015011215404114490871420.0.0.0_ep2d_diff_3scan_trace_p2_20150112153840_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0013726250/20161115_4163094/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016111513570850700958667.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016111513570850700958667.0.0.0_ep2d_diff_3scan_trace_p2_20161115135255_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0010957448/20120428_2900621/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.201204280936576983508645.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.201204280936576983508645.0.0.0_ep2d_diff_3scan_trace_p2_20120428093502_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0005768640/20150416_3663784/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015041607244246524101339.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015041607244246524101339.0.0.0_ep2d_diff_3scan_trace_p2_20150416072316_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0004751884/20160825_4085988/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016082505265456580980765.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016082505265456580980765.0.0.0_ep2d_diff_3scan_trace_p2_20160825052535_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0013806831/20161231_4205208/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016123103171570886101345.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016123103171570886101345.0.0.0_ep2d_diff_3scan_trace_p2_20161231031314_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0013561340/20160814_4075674/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016081423232347130234856.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016081423232347130234856.0.0.0_ep2d_diff_3scan_trace_p2_20160814232122_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0000911666/20170318_4279828/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017031803434419578756163.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2017031803434419578756163.0.0.0_ep2d_diff_3scan_trace_p2_20170318034215_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0011420316/20130204_3078550/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2013020411064122454430395.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2013020411064122454430395.0.0.0_ep2d_diff_M128_b0_1000_DIN_20130204110226_4.nii.gz does not contain 4 dimensions but has shape (128, 128, 25). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0008505020/20161024_4142199/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.201610241554179766291780.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40186.201610241554179766291780.0.0.0_ep2d_diff_M128_b0_1000_DIN_20161024155220_3.nii.gz does not contain 4 dimensions but has shape (128, 128, 25). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0012752479/20150509_3683394/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015050911245686910728617.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015050911245686910728617.0.0.0_ep2d_diff_3scan_trace_p2_20150509112322_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0013982095/20170401_4293517/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017040120033418406712910.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2017040120033418406712910.0.0.0_ep2d_diff_3scan_trace_p2_20170401200209_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 21). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0001728245/20160602_4011937/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2016060213155013546642903.0.0.0/resolve_3scan_trace_tra_176_p2_ADC_1.3.12.2.1107.5.2.18.41437.2016060213155013546642903.0.0.0_resolve_3scan_trace_tra_176_p2_20160602131359_3.nii.gz does not contain 4 dimensions but has shape (176, 176, 20). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0007956525/20121210_3044374/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2012121017501123667780863.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2012121017501123667780863.0.0.0_ep2d_diff_M128_b0_1000_DIN_20121210174825_3.nii.gz does not contain 4 dimensions but has shape (128, 128, 25). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0012580430/20150124_3598121/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015012411411240581387359.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015012411411240581387359.0.0.0_ep2d_diff_3scan_trace_p2_20150124113949_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0002923041/20170703_4379063/Diffusion_tra_3mm_ADC__1.3.12.2.1107.5.2.18.141120.2017070310463983789143341.0.0.0/Diffusion_tra_3mm_ADC_1.3.12.2.1107.5.2.18.141120.2017070310463983789143341.0.0.0_Diffusion_tra_3mm_20170703104502_3.nii.gz does not contain 4 dimensions but has shape (376, 376, 42). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0007803001/20130605_3160831/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013060518553430651457279.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2013060518553430651457279.0.0.0_ep2d_diff_3scan_trace_p2_20130605185301_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0001305751/20160423_3978120/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016042317505420514655212.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016042317505420514655212.0.0.0_ep2d_diff_3scan_trace_p2_20160423174841_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0010721312/20151028_3825190/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015102812275277228458082.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015102812275277228458082.0.0.0_ep2d_diff_3scan_trace_p2_20151028122457_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0013250558/20160301_3930264/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016030116515490319838509.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2016030116515490319838509.0.0.0_ep2d_diff_M128_b0_1000_DIN_20160301164038_3.nii.gz does not contain 4 dimensions but has shape (128, 128, 25). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0001120794/20170116_4218415/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017011615131252371173003.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2017011615131252371173003.0.0.0_ep2d_diff_3scan_trace_p2_20170116151147_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0010997857/20120523_2915739/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2012052309145187437608354.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2012052309145187437608354.0.0.0_ep2d_diff_M128_b0_1000_DIN_20120523091246_3.nii.gz does not contain 4 dimensions but has shape (128, 128, 25). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0008436487/20170612_4358040/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2017061213340585324746682.0.0.0/resolve_3scan_trace_tra_176_p2_ADC_1.3.12.2.1107.5.2.18.41437.2017061213340585324746682.0.0.0_resolve_3scan_trace_tra_176_p2_20170612133232_3.nii.gz does not contain 4 dimensions but has shape (176, 176, 20). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0012781541/20150526_3696011/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2015052615191539489540002.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2015052615191539489540002.0.0.0_ep2d_diff_M128_b0_1000_DIN_20150526151714_3.nii.gz does not contain 4 dimensions but has shape (128, 128, 25). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0000481858/20121025_3013771/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2012102507535097175206178.0.0.0/resolve_3scan_trace_tra_176_p2_ADC_1.3.12.2.1107.5.2.18.41437.2012102507535097175206178.0.0.0_resolve_3scan_trace_tra_176_p2_20121025075220_3.nii.gz does not contain 4 dimensions but has shape (176, 176, 20). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0011293764/20130708_3183238/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013070810395476199318553.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2013070810395476199318553.0.0.0_ep2d_diff_3scan_trace_p2_20130708103814_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 21). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0012870480/20150715_3739282/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2015071517302852321687772.0.0.0/resolve_3scan_trace_tra_176_p2_ADC_1.3.12.2.1107.5.2.18.41437.2015071517302852321687772.0.0.0_resolve_3scan_trace_tra_176_p2_20150715172801_3.nii.gz does not contain 4 dimensions but has shape (176, 176, 20). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0013164171/20160114_3888741/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.2016011408422394680007345.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40186.2016011408422394680007345.0.0.0_ep2d_diff_M128_b0_1000_DIN_20160114084021_3.nii.gz does not contain 4 dimensions but has shape (128, 128, 20). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0082364672/20170112_4215453/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2017011211103382964145931.0.0.0/resolve_3scan_trace_tra_176_p2_ADC_1.3.12.2.1107.5.2.18.41437.2017011211103382964145931.0.0.0_resolve_3scan_trace_tra_176_p2_20170112110900_3.nii.gz does not contain 4 dimensions but has shape (176, 176, 20). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0000442968/20151109_3835318/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015110920165992102092193.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015110920165992102092193.0.0.0_ep2d_diff_3scan_trace_p2_20151109201528_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0013017152/20151017_3816432/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015101723393844339265263.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015101723393844339265263.0.0.0_ep2d_diff_3scan_trace_p2_20151017233745_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0000830267/20140331_3374880/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.20140331175722548233096.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.20140331175722548233096.0.0.0_ep2d_diff_M128_b0_1000_DIN_20140331175529_3.nii.gz does not contain 4 dimensions but has shape (128, 128, 25). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0004905113/20150501_3677174/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015050113384736814330990.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015050113384736814330990.0.0.0_ep2d_diff_3scan_trace_p2_20150501133729_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0011357428/20121222_3052849/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2012122213291045397701374.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2012122213291045397701374.0.0.0_ep2d_diff_M128_b0_1000_DIN_20121222132715_3.nii.gz does not contain 4 dimensions but has shape (128, 128, 25). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0003938921/20141229_3578338/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2014122912054939880982670.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2014122912054939880982670.0.0.0_ep2d_diff_M128_b0_1000_DIN_20141229120415_3.nii.gz does not contain 4 dimensions but has shape (128, 128, 25). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0012873870/20150717_3741110/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.2015071714094897961545459.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40186.2015071714094897961545459.0.0.0_ep2d_diff_M128_b0_1000_DIN_20150717140436_3.nii.gz does not contain 4 dimensions but has shape (128, 128, 20). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0013184407/20160127_3900057/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016012709384890487917933.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2016012709384890487917933.0.0.0_ep2d_diff_M128_b0_1000_DIN_20160127093703_3.nii.gz does not contain 4 dimensions but has shape (128, 128, 25). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0004769619/20160325_3952357/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016032507024493479801339.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016032507024493479801339.0.0.0_ep2d_diff_3scan_trace_p2_20160325065931_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 21). Skipping this one.
image of patient /home/bule/berner_daten_analyse/data/nifti/0013915045/20170226_4259441/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017022622555492999245605.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2017022622555492999245605.0.0.0_ep2d_diff_3scan_trace_p2_20170226225440_3.nii.gz does not contain 4 dimensions but has shape (192, 192, 19). Skipping this one.

{9157646: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0009157646/20131022_3257263/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013102220135264655603624.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2013102220135264655603624.0.0.0_ep2d_diff_3scan_trace_p2_20131022201218_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0009157646/20131022_3257263/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2013102220135264655503623.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2013102220135264655503623.0.0.0_ep2d_diff_3scan_trace_p2_20131022201218_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0009157646/20131022_3257263/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.201310222030425034215951.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.201310222030425034215951.0.0.0_t1_se_r_tra_KM_20131022201218_19.nii.gz'},
 1029355: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0001029355/20150421_3667803/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015042113370162060649641.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015042113370162060649641.0.0.0_ep2d_diff_3scan_trace_p2_20150421133546_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0001029355/20150421_3667803/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015042113370162060549640.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2015042113370162060549640.0.0.0_ep2d_diff_3scan_trace_p2_20150421133546_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0001029355/20150421_3667803/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2015042113510136468760962.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2015042113510136468760962.0.0.0_t1_se_r_tra_KM_20150421133546_14.nii.gz'},
 3410390: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0003410390/20170418_4309773/ep2d_diff_tra_resolve_ADC__1.3.12.2.1107.5.2.18.41102.2017041807294828614202566.0.0.0/ep2d_diff_tra_resolve_ADC_1.3.12.2.1107.5.2.18.41102.2017041807294828614202566.0.0.0_ep2d_diff_tra_resolve_20170418071959_8.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0003410390/20170418_4309773/ep2d_diff_tra_resolve_TRACEW__1.3.12.2.1107.5.2.18.41102.2017041807294828614002565.0.0.0/ep2d_diff_tra_resolve_TRACEW_1.3.12.2.1107.5.2.18.41102.2017041807294828614002565.0.0.0_ep2d_diff_tra_resolve_20170418071959_7.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0003410390/20170418_4309773/t1_se_tra__1.3.12.2.1107.5.2.18.41102.2017041807361572712307498.0.0.0/t1_se_tra_1.3.12.2.1107.5.2.18.41102.2017041807361572712307498.0.0.0_t1_se_tra_20170418071959_9.nii.gz'},
 13361457: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0013361457/20160427_3981418/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016042712312612374340705.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016042712312612374340705.0.0.0_ep2d_diff_3scan_trace_p2_20160427122854_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0013361457/20160427_3981418/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016042712312612374240704.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2016042712312612374240704.0.0.0_ep2d_diff_3scan_trace_p2_20160427122854_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0013361457/20160427_3981418/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.201604271245251290051880.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.201604271245251290051880.0.0.0_t1_se_r_tra_KM_20160427122854_14.nii.gz'},
 13341421: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0013341421/20160417_3971699/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016041713384993450322446.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2016041713384993450322446.0.0.0_ep2d_diff_M128_b0_1000_DIN_20160417133658_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0013341421/20160417_3971699/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2016041713384993450022445.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2016041713384993450022445.0.0.0_ep2d_diff_M128_b0_1000_DIN_20160417133658_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0013341421/20160417_3971699/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2016041713522164618633945.0.0.0/t1_fl2d_tra_1.3.12.2.1107.5.2.36.40270.2016041713522164618633945.0.0.0_t1_fl2d_tra_20160417133658_16.nii.gz'},
 11069368: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0011069368/20120629_2939441/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012062920264377595808813.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2012062920264377595808813.0.0.0_ep2d_diff_3scan_trace_p2_20120629202348_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0011069368/20120629_2939441/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2012062920264377595708812.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2012062920264377595708812.0.0.0_ep2d_diff_3scan_trace_p2_20120629202348_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0011069368/20120629_2939441/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.201206292045263211620230.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.201206292045263211620230.0.0.0_t1_se_r_tra_KM_20120629202348_14.nii.gz'},
 13105663: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0013105663/20151208_3860103/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2015120819281435262084705.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2015120819281435262084705.0.0.0_ep2d_diff_M128_b0_1000_DIN_20151208192622_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0013105663/20151208_3860103/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2015120819281435261684704.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2015120819281435261684704.0.0.0_ep2d_diff_M128_b0_1000_DIN_20151208192622_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0013105663/20151208_3860103/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.201512081943487855397020.0.0.0/t1_fl2d_tra_1.3.12.2.1107.5.2.36.40270.201512081943487855397020.0.0.0_t1_fl2d_tra_20151208192622_16.nii.gz'},
 7815360: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0007815360/20140614_3430160/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2014061410232886392209257.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2014061410232886392209257.0.0.0_ep2d_diff_3scan_trace_p2_20140614102146_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0007815360/20140614_3430160/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2014061410232886392009256.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2014061410232886392009256.0.0.0_ep2d_diff_3scan_trace_p2_20140614102146_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0007815360/20140614_3430160/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2014061410373027067720586.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2014061410373027067720586.0.0.0_t1_se_r_tra_KM_20140614102146_13.nii.gz'},
 13904620: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0013904620/20170220_4253696/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017022019533284029464194.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2017022019533284029464194.0.0.0_ep2d_diff_3scan_trace_p2_20170220195048_4.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0013904620/20170220_4253696/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2017022019533284029364193.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2017022019533284029364193.0.0.0_ep2d_diff_3scan_trace_p2_20170220195048_3.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0013904620/20170220_4253696/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2017022020211692502877687.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2017022020211692502877687.0.0.0_t1_se_r_tra_KM_20170220195048_19.nii.gz'},
 11737328: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0011737328/20130818_3211640/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013081806581426018001342.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2013081806581426018001342.0.0.0_ep2d_diff_3scan_trace_p2_20130818065620_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0011737328/20130818_3211640/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2013081806581426017901341.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2013081806581426017901341.0.0.0_ep2d_diff_3scan_trace_p2_20130818065620_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0011737328/20130818_3211640/t2_blade_tra__1.3.12.2.1107.5.2.30.27272.2013081807015949798804016.0.0.0/t2_blade_tra_1.3.12.2.1107.5.2.30.27272.2013081807015949798804016.0.0.0_t2_blade_tra_20130818065620_4.nii.gz'},
 13213261: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0013213261/20160210_3912721/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016021006173840652039151.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016021006173840652039151.0.0.0_ep2d_diff_3scan_trace_p2_20160210061515_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0013213261/20160210_3912721/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016021006173840651939150.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2016021006173840651939150.0.0.0_ep2d_diff_3scan_trace_p2_20160210061515_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0013213261/20160210_3912721/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2016021006445913589655113.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2016021006445913589655113.0.0.0_t1_se_r_tra_KM_20160210061515_31.nii.gz'},
 12524182: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0012524182/20150112_3587862/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015011215404114490871420.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015011215404114490871420.0.0.0_ep2d_diff_3scan_trace_p2_20150112153840_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0012524182/20150112_3587862/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015011215404114490771419.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2015011215404114490771419.0.0.0_ep2d_diff_3scan_trace_p2_20150112153840_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0012524182/20150112_3587862/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2015011215545061461682748.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2015011215545061461682748.0.0.0_t1_se_r_tra_KM_20150112153840_14.nii.gz'},
 13726250: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0013726250/20161115_4163094/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016111513570850700958667.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016111513570850700958667.0.0.0_ep2d_diff_3scan_trace_p2_20161115135255_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0013726250/20161115_4163094/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016111513570850700858666.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2016111513570850700858666.0.0.0_ep2d_diff_3scan_trace_p2_20161115135255_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0013726250/20161115_4163094/Tirm_tra_fs_TI_2500__1.3.12.2.1107.5.2.30.27272.201611151359397741760718.0.0.0/Tirm_tra_fs_TI_2500_1.3.12.2.1107.5.2.30.27272.201611151359397741760718.0.0.0_Tirm_tra_fs_TI_2500_20161115135255_4.nii.gz'},
 10957448: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0010957448/20120428_2900621/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.201204280936576983508645.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.201204280936576983508645.0.0.0_ep2d_diff_3scan_trace_p2_20120428093502_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0010957448/20120428_2900621/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.201204280936576983308644.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.201204280936576983308644.0.0.0_ep2d_diff_3scan_trace_p2_20120428093502_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0010957448/20120428_2900621/t2_blade_tra__1.3.12.2.1107.5.2.30.27272.2012042809393419148610862.0.0.0/t2_blade_tra_1.3.12.2.1107.5.2.30.27272.2012042809393419148610862.0.0.0_t2_blade_tra_20120428093502_4.nii.gz'},
 5768640: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0005768640/20150416_3663784/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015041607244246524101339.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015041607244246524101339.0.0.0_ep2d_diff_3scan_trace_p2_20150416072316_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0005768640/20150416_3663784/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015041607244246524001338.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2015041607244246524001338.0.0.0_ep2d_diff_3scan_trace_p2_20150416072316_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0005768640/20150416_3663784/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2015041607382548399912660.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2015041607382548399912660.0.0.0_t1_se_r_tra_KM_20150416072316_14.nii.gz'},
 4751884: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0004751884/20160825_4085988/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016082505265456580980765.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016082505265456580980765.0.0.0_ep2d_diff_3scan_trace_p2_20160825052535_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0004751884/20160825_4085988/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016082505265456580880764.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2016082505265456580880764.0.0.0_ep2d_diff_3scan_trace_p2_20160825052535_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0004751884/20160825_4085988/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2016082505401510906191940.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2016082505401510906191940.0.0.0_t1_se_r_tra_KM_20160825052535_12.nii.gz'},
 13806831: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0013806831/20161231_4205208/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016123103171570886101345.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016123103171570886101345.0.0.0_ep2d_diff_3scan_trace_p2_20161231031314_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0013806831/20161231_4205208/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016123103171570886001344.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2016123103171570886001344.0.0.0_ep2d_diff_3scan_trace_p2_20161231031314_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0013806831/20161231_4205208/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2016123103403826978614386.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2016123103403826978614386.0.0.0_t1_se_r_tra_KM_20161231031314_15.nii.gz'},
 13561340: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0013561340/20160814_4075674/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016081423232347130234856.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016081423232347130234856.0.0.0_ep2d_diff_3scan_trace_p2_20160814232122_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0013561340/20160814_4075674/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016081423232347130034855.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2016081423232347130034855.0.0.0_ep2d_diff_3scan_trace_p2_20160814232122_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0013561340/20160814_4075674/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2016081423401756138141592.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2016081423401756138141592.0.0.0_t1_se_r_tra_KM_20160814232122_22.nii.gz'},
 911666: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0000911666/20170318_4279828/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017031803434419578756163.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2017031803434419578756163.0.0.0_ep2d_diff_3scan_trace_p2_20170318034215_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0000911666/20170318_4279828/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2017031803434419578656162.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2017031803434419578656162.0.0.0_ep2d_diff_3scan_trace_p2_20170318034215_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0000911666/20170318_4279828/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2017031803570532417566553.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2017031803570532417566553.0.0.0_t1_se_r_tra_KM_20170318034215_14.nii.gz'},
 11420316: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0011420316/20130204_3078550/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2013020411064122454430395.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2013020411064122454430395.0.0.0_ep2d_diff_M128_b0_1000_DIN_20130204110226_4.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0011420316/20130204_3078550/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2013020411064122454030394.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2013020411064122454030394.0.0.0_ep2d_diff_M128_b0_1000_DIN_20130204110226_3.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0011420316/20130204_3078550/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2013020411212991837441954.0.0.0/t1_fl2d_tra_1.3.12.2.1107.5.2.36.40270.2013020411212991837441954.0.0.0_t1_fl2d_tra_20130204110226_15.nii.gz'},
 8505020: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0008505020/20161024_4142199/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.201610241554179766291780.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40186.201610241554179766291780.0.0.0_ep2d_diff_M128_b0_1000_DIN_20161024155220_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0008505020/20161024_4142199/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.201610241554179766191779.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40186.201610241554179766191779.0.0.0_ep2d_diff_M128_b0_1000_DIN_20161024155220_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0008505020/20161024_4142199/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40186.2016102416073279025003279.0.0.0/t1_fl2d_tra_1.3.12.2.1107.5.2.36.40186.2016102416073279025003279.0.0.0_t1_fl2d_tra_20161024155220_14.nii.gz'},
 12752479: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0012752479/20150509_3683394/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015050911245686910728617.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015050911245686910728617.0.0.0_ep2d_diff_3scan_trace_p2_20150509112322_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0012752479/20150509_3683394/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015050911245686910628616.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2015050911245686910628616.0.0.0_ep2d_diff_3scan_trace_p2_20150509112322_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0012752479/20150509_3683394/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2015050911432419210041249.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2015050911432419210041249.0.0.0_t1_se_r_tra_KM_20150509112322_14.nii.gz'},

In [ ]:
# import os
# import nibabel as nib
# import pandas as pd

# # THE SHAPE OF THE IMAGES SHOULD BE 3 
# filter_index_pos = 3

# dfnew = df_only_3.copy()
# dfnew['sel_b1000'] = dfnew['Full_Path_Nifti']

# for idx, path in df_only_3['Full_Path_Nifti'].items():
#     dwi = nib.load(path)
#     dwi_shape = dwi.get_fdata().shape

#     # If it's 4D, extract the last volume (assumed b1000)
#     if len(dwi_shape) == filter_index_pos + 1:
#         print(f"{path} is 4D → extracting b1000 (last volume)")
#         b1000_sequence = dwi.get_fdata()[..., -1]
#         new_nifti = nib.Nifti1Image(b1000_sequence, dwi.affine, dwi.header)

#         nifti_folder_path, dwi_file_name = os.path.split(path)
#         new_file_path = os.path.join(nifti_folder_path, "b1000-extracted-" + dwi_file_name)

#         if not os.path.exists(new_file_path):
#             nib.save(new_nifti, new_file_path)

#         dfnew.loc[idx, 'sel_b1000'] = new_file_path

#     elif len(dwi_shape) == 3:
#         # Already 3D, keep as-is
#         dfnew.loc[idx, 'sel_b1000'] = path
#     else:
#         print(f"Skipping {path}: unexpected shape {dwi_shape}")

# ########## create new dataframe with the new paths
# dict_paths = {}
# for index, row in dfnew.iterrows():
#     patient_id = row['Patient_ID']
#     if patient_id not in dict_paths:
#         dict_paths[patient_id] = {}
#     dict_paths[patient_id][row['Modality']] = row['sel_b1000']

/home/bule/berner_daten_analyse/data/nifti/0000076813/20170614_4361718/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2017061416562196724753041.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40186.2017061416562196724753041.0.0.0_ep2d_diff_M128_b0_1000_DIN_20170614164701_6.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0000442968/20151109_3835318/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015110920165992101992192.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2015110920165992101992192.0.0.0_ep2d_diff_3scan_trace_p2_20151109201528_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0000481858/20121025_3013771/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.2012102507535097175006177.0.0.0/resolve_3scan_trace_tra_176_p2_TRACEW_1.3.12.2.1107.5.2.18.41437.2012102507535097175006177.0.0.0_resolve_3scan_trace_tra_176_p2_20121025075220_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0000516341/20160211_3914130/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2016021109502693022615340.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40186.2016021109502693022615340.0.0.0_ep2d_diff_M128_b0_1000_DIN_20160211094700_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0000653853/20161216_4193466/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2016121611003455620444483.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40186.2016121611003455620444483.0.0.0_ep2d_diff_M128_b0_1000_DIN_20161216105853_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0000744018/20140321_3307663/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2014032112104737923044060.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40186.2014032112104737923044060.0.0.0_ep2d_diff_M128_b0_1000_DIN_20140321120529_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0000768081/20130110_3061277/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2013011009244276086119640.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2013011009244276086119640.0.0.0_ep2d_diff_M128_b0_1000_DIN_20130110092000_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0000801402/20161123_4171427/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2016112315454677328107737.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2016112315454677328107737.0.0.0_ep2d_diff_M128_b0_1000_DIN_20161123154259_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0000830267/20140331_3374880/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.20140331175722547933095.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.20140331175722547933095.0.0.0_ep2d_diff_M128_b0_1000_DIN_20140331175529_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0000842389/20140312_3359892/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.2014031212351314054924900.0.0.0/resolve_3scan_trace_tra_176_p2_TRACEW_1.3.12.2.1107.5.2.18.41437.2014031212351314054924900.0.0.0_resolve_3scan_trace_tra_176_p2_20140312123324_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0000864099/20170810_4414948/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2017081009152314774025143.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2017081009152314774025143.0.0.0_ep2d_diff_M128_b0_1000_DIN_20170810091328_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0000876763/20120405_2888249/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2012040521123029117344433.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2012040521123029117344433.0.0.0_ep2d_diff_M128_b0_1000_DIN_20120405204237_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0000911666/20170318_4279828/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2017031803434419578656162.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2017031803434419578656162.0.0.0_ep2d_diff_3scan_trace_p2_20170318034215_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0000975885/20150109_3585477/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2015010916452393266706834.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2015010916452393266706834.0.0.0_ep2d_diff_M128_b0_1000_DIN_20150109164049_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0000991155/20150411_3660367/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015041118321818686079881.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2015041118321818686079881.0.0.0_ep2d_diff_3scan_trace_p2_20150411183042_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0000996254/20130724_3195639/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2013072421213631171236904.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2013072421213631171236904.0.0.0_ep2d_diff_3scan_trace_p2_20130724211119_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001029355/20150421_3667803/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015042113370162060549640.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2015042113370162060549640.0.0.0_ep2d_diff_3scan_trace_p2_20150421133546_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001063871/20131017_3253819/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2013101716025958260711548.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2013101716025958260711548.0.0.0_ep2d_diff_M128_b0_1000_DIN_20131017160111_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001071106/20161019_4136980/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016101904144578314354823.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2016101904144578314354823.0.0.0_ep2d_diff_3scan_trace_p2_20161019041259_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001097032/20150313_3637563/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.201503130551264238201339.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.201503130551264238201339.0.0.0_ep2d_diff_3scan_trace_p2_20150313054953_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001120794/20170116_4218415/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2017011615131252370973002.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2017011615131252370973002.0.0.0_ep2d_diff_3scan_trace_p2_20170116151147_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001192469/20140123_3321953/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2014012307161658156701374.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2014012307161658156701374.0.0.0_ep2d_diff_M128_b0_1000_DIN_20140123071124_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001241478/20160609_4018223/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.2016060910062519805622381.0.0.0/resolve_3scan_trace_tra_176_p2_TRACEW_1.3.12.2.1107.5.2.18.41437.2016060910062519805622381.0.0.0_resolve_3scan_trace_tra_176_p2_20160609100423_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001305751/20160423_3978120/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016042317505420514555211.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2016042317505420514555211.0.0.0_ep2d_diff_3scan_trace_p2_20160423174841_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001313428/20160721_4055894/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.201607210859572842708388.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40186.201607210859572842708388.0.0.0_ep2d_diff_M128_b0_1000_DIN_20160721085746_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001344072/20151031_3827791/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015103112295884515652682.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2015103112295884515652682.0.0.0_ep2d_diff_3scan_trace_p2_20151031122208_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001357840/20170130_4232882/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2017013022185215800401373.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2017013022185215800401373.0.0.0_ep2d_diff_M128_b0_1000_DIN_20170130221641_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001397044/20161019_4137895/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2016101916162136923747280.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40186.2016101916162136923747280.0.0.0_ep2d_diff_M128_b0_1000_DIN_20161019161434_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001424025/20170712_4389337/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2017071220392256093327041.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2017071220392256093327041.0.0.0_ep2d_diff_M128_b0_1000_DIN_20170712203302_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001428012/20160927_4117379/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.2016092715122564973549281.0.0.0/resolve_3scan_trace_tra_176_p2_TRACEW_1.3.12.2.1107.5.2.18.41437.2016092715122564973549281.0.0.0_resolve_3scan_trace_tra_176_p2_20160927151038_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001489860/20120330_2884717/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2012033020594734603410302.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2012033020594734603410302.0.0.0_ep2d_diff_3scan_trace_p2_20120330205829_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001494589/20130322_3111977/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2013032210132943978417523.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2013032210132943978417523.0.0.0_ep2d_diff_3scan_trace_p2_20130322101035_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001495976/20160610_4019462/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016061010400597860750327.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2016061010400597860750327.0.0.0_ep2d_diff_3scan_trace_p2_20160610103417_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001657011/20160313_3941113/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016031316312397417462335.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2016031316312397417462335.0.0.0_ep2d_diff_3scan_trace_p2_20160313162717_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001679589/20160714_4050235/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016071412100665705553359.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2016071412100665705553359.0.0.0_ep2d_diff_3scan_trace_p2_20160714120359_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001728245/20160602_4011937/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.2016060213155013546442902.0.0.0/resolve_3scan_trace_tra_176_p2_TRACEW_1.3.12.2.1107.5.2.18.41437.2016060213155013546442902.0.0.0_resolve_3scan_trace_tra_176_p2_20160602131359_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001746421/20120305_2868060/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2012030520305325508491476.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2012030520305325508491476.0.0.0_ep2d_diff_M128_b0_1000_DIN_20120305202905_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001775707/20150301_3626826/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015030113162725907554790.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2015030113162725907554790.0.0.0_ep2d_diff_3scan_trace_p2_20150301131409_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001829939/20150718_3741531/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015071807190941239701338.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2015071807190941239701338.0.0.0_ep2d_diff_3scan_trace_p2_20150718071712_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001870394/20131101_3264798/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.201311011136166347429830.0.0.0/resolve_3scan_trace_tra_176_p2_TRACEW_1.3.12.2.1107.5.2.18.41437.201311011136166347429830.0.0.0_resolve_3scan_trace_tra_176_p2_20131101113433_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001922173/20170622_4369392/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.201706221248259974123766.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.201706221248259974123766.0.0.0_ep2d_diff_M128_b0_1000_DIN_20170622124631_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0001926713/20151023_3821340/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2015102312112178347286360.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2015102312112178347286360.0.0.0_ep2d_diff_M128_b0_1000_DIN_20151023120227_5.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0002013010/20131012_3249790/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2013101202134197237601340.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2013101202134197237601340.0.0.0_ep2d_diff_3scan_trace_p2_20131012021144_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0002074265/20161010_4129033/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2016101019451235014619206.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2016101019451235014619206.0.0.0_ep2d_diff_M128_b0_1000_DIN_20161010194310_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0002081504/20130209_3082905/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2013020908431267697807878.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2013020908431267697807878.0.0.0_ep2d_diff_M128_b0_1000_DIN_20130209084131_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0002109603/20160531_4010600/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2016053119584863836240365.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2016053119584863836240365.0.0.0_ep2d_diff_M128_b0_1000_DIN_20160531195650_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0002334038/20130417_3128688/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2013041720054373987252132.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2013041720054373987252132.0.0.0_ep2d_diff_M128_b0_1000_DIN_20130417200353_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0002457849/20130515_3146971/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2013051516054152085062547.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2013051516054152085062547.0.0.0_ep2d_diff_3scan_trace_p2_20130515160406_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0002500051/20141017_3523243/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2014101718255361825373352.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2014101718255361825373352.0.0.0_ep2d_diff_M128_b0_1000_DIN_20141017182401_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0002593122/20160922_4112749/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.2016092211315357192544946.0.0.0/resolve_3scan_trace_tra_176_p2_TRACEW_1.3.12.2.1107.5.2.18.41437.2016092211315357192544946.0.0.0_resolve_3scan_trace_tra_176_p2_20160922112839_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0002614103/20150416_3664397/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015041614121712011660001.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2015041614121712011660001.0.0.0_ep2d_diff_3scan_trace_p2_20150416141049_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0002663120/20120316_2875713/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2012031616580116587925437.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2012031616580116587925437.0.0.0_ep2d_diff_3scan_trace_p2_20120316165416_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0002679663/20170908_4442498/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2017090819220625955197753.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2017090819220625955197753.0.0.0_ep2d_diff_M128_b0_1000_DIN_20170908192020_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0002782782/20160119_3893609/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2016011915141626838210484.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2016011915141626838210484.0.0.0_ep2d_diff_M128_b0_1000_DIN_20160119150737_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0002810883/20150630_3726400/resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12.2.1107.5.2.18.41437.2015063016263682869369524.0.0.0/resolve_3scan_trace_tra_176_p2_TRACEW_1.3.12.2.1107.5.2.18.41437.2015063016263682869369524.0.0.0_resolve_3scan_trace_tra_176_p2_20150630162452_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0002840065/20141219_3502193/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2014121912432017685041945.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2014121912432017685041945.0.0.0_ep2d_diff_M128_b0_1000_DIN_20141219123530_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0002910306/20151002_3804610/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.2015100214524256289576686.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40186.2015100214524256289576686.0.0.0_ep2d_diff_M128_b0_1000_DIN_20151002145051_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0002920026/20140906_3491955/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2014090611542476372529470.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2014090611542476372529470.0.0.0_ep2d_diff_3scan_trace_p2_20140906115211_2.nii.gz is 4D → extracting b1000 (last volume)
/home/bule/berner_daten_analyse/data/nifti/0002923041/20170703_4379063/Diffusion_tra_3mm_TRACEW__1.3.12.2.1107.5.2.18.141120.2017070310463983788943340.0.0.0/Diffusion_tra_3mm_TRACEW_1.3.12.2.1107.5.2.18.141120.2017070310463983788943340.0.0.0_Diffusion_tra_3mm_20170703104502_2.nii.gz is 4D → extracting b1000 (last volume)

In [39]:
dict_paths_new={}
valid_pids=set(only_2_df_selection_dwi['Patient_ID'])
for pid, paths in dict_paths.items():
    if int(pid) in valid_pids:
        dict_paths_new[pid]=paths
dict_paths_new

{9157646: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0009157646/20131022_3257263/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013102220135264655603624.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2013102220135264655603624.0.0.0_ep2d_diff_3scan_trace_p2_20131022201218_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0009157646/20131022_3257263/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2013102220135264655503623.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2013102220135264655503623.0.0.0_ep2d_diff_3scan_trace_p2_20131022201218_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0009157646/20131022_3257263/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.201310222030425034215951.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.201310222030425034215951.0.0.0_t1_se_r_tra_KM_20131022201218_19.nii.gz'},
 1029355: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0001029355/20150421_3667803/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015042113370162060649641.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015042113370162060649641.0.0.0_ep2d_diff_3scan_trace_p2_20150421133546_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0001029355/20150421_3667803/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015042113370162060549640.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2015042113370162060549640.0.0.0_ep2d_diff_3scan_trace_p2_20150421133546_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0001029355/20150421_3667803/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2015042113510136468760962.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2015042113510136468760962.0.0.0_t1_se_r_tra_KM_20150421133546_14.nii.gz'},
 3410390: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0003410390/20170418_4309773/ep2d_diff_tra_resolve_ADC__1.3.12.2.1107.5.2.18.41102.2017041807294828614202566.0.0.0/ep2d_diff_tra_resolve_ADC_1.3.12.2.1107.5.2.18.41102.2017041807294828614202566.0.0.0_ep2d_diff_tra_resolve_20170418071959_8.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0003410390/20170418_4309773/ep2d_diff_tra_resolve_TRACEW__1.3.12.2.1107.5.2.18.41102.2017041807294828614002565.0.0.0/ep2d_diff_tra_resolve_TRACEW_1.3.12.2.1107.5.2.18.41102.2017041807294828614002565.0.0.0_ep2d_diff_tra_resolve_20170418071959_7.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0003410390/20170418_4309773/t1_se_tra__1.3.12.2.1107.5.2.18.41102.2017041807361572712307498.0.0.0/t1_se_tra_1.3.12.2.1107.5.2.18.41102.2017041807361572712307498.0.0.0_t1_se_tra_20170418071959_9.nii.gz'},
 13361457: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0013361457/20160427_3981418/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016042712312612374340705.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016042712312612374340705.0.0.0_ep2d_diff_3scan_trace_p2_20160427122854_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0013361457/20160427_3981418/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016042712312612374240704.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2016042712312612374240704.0.0.0_ep2d_diff_3scan_trace_p2_20160427122854_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0013361457/20160427_3981418/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.201604271245251290051880.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.201604271245251290051880.0.0.0_t1_se_r_tra_KM_20160427122854_14.nii.gz'},
 13341421: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0013341421/20160417_3971699/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016041713384993450322446.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2016041713384993450322446.0.0.0_ep2d_diff_M128_b0_1000_DIN_20160417133658_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0013341421/20160417_3971699/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2016041713384993450022445.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2016041713384993450022445.0.0.0_ep2d_diff_M128_b0_1000_DIN_20160417133658_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0013341421/20160417_3971699/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2016041713522164618633945.0.0.0/t1_fl2d_tra_1.3.12.2.1107.5.2.36.40270.2016041713522164618633945.0.0.0_t1_fl2d_tra_20160417133658_16.nii.gz'},
 11069368: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0011069368/20120629_2939441/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012062920264377595808813.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2012062920264377595808813.0.0.0_ep2d_diff_3scan_trace_p2_20120629202348_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0011069368/20120629_2939441/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2012062920264377595708812.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2012062920264377595708812.0.0.0_ep2d_diff_3scan_trace_p2_20120629202348_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0011069368/20120629_2939441/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.201206292045263211620230.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.201206292045263211620230.0.0.0_t1_se_r_tra_KM_20120629202348_14.nii.gz'},
 13105663: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0013105663/20151208_3860103/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2015120819281435262084705.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2015120819281435262084705.0.0.0_ep2d_diff_M128_b0_1000_DIN_20151208192622_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0013105663/20151208_3860103/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2015120819281435261684704.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2015120819281435261684704.0.0.0_ep2d_diff_M128_b0_1000_DIN_20151208192622_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0013105663/20151208_3860103/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.201512081943487855397020.0.0.0/t1_fl2d_tra_1.3.12.2.1107.5.2.36.40270.201512081943487855397020.0.0.0_t1_fl2d_tra_20151208192622_16.nii.gz'},
 7815360: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0007815360/20140614_3430160/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2014061410232886392209257.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2014061410232886392209257.0.0.0_ep2d_diff_3scan_trace_p2_20140614102146_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0007815360/20140614_3430160/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2014061410232886392009256.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2014061410232886392009256.0.0.0_ep2d_diff_3scan_trace_p2_20140614102146_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0007815360/20140614_3430160/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2014061410373027067720586.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2014061410373027067720586.0.0.0_t1_se_r_tra_KM_20140614102146_13.nii.gz'},
 13904620: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0013904620/20170220_4253696/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017022019533284029464194.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2017022019533284029464194.0.0.0_ep2d_diff_3scan_trace_p2_20170220195048_4.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0013904620/20170220_4253696/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2017022019533284029364193.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2017022019533284029364193.0.0.0_ep2d_diff_3scan_trace_p2_20170220195048_3.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0013904620/20170220_4253696/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2017022020211692502877687.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2017022020211692502877687.0.0.0_t1_se_r_tra_KM_20170220195048_19.nii.gz'},
 11737328: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0011737328/20130818_3211640/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013081806581426018001342.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2013081806581426018001342.0.0.0_ep2d_diff_3scan_trace_p2_20130818065620_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0011737328/20130818_3211640/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2013081806581426017901341.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2013081806581426017901341.0.0.0_ep2d_diff_3scan_trace_p2_20130818065620_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0011737328/20130818_3211640/t2_blade_tra__1.3.12.2.1107.5.2.30.27272.2013081807015949798804016.0.0.0/t2_blade_tra_1.3.12.2.1107.5.2.30.27272.2013081807015949798804016.0.0.0_t2_blade_tra_20130818065620_4.nii.gz'},
 13213261: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0013213261/20160210_3912721/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016021006173840652039151.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016021006173840652039151.0.0.0_ep2d_diff_3scan_trace_p2_20160210061515_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0013213261/20160210_3912721/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016021006173840651939150.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2016021006173840651939150.0.0.0_ep2d_diff_3scan_trace_p2_20160210061515_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0013213261/20160210_3912721/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2016021006445913589655113.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2016021006445913589655113.0.0.0_t1_se_r_tra_KM_20160210061515_31.nii.gz'},
 12524182: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0012524182/20150112_3587862/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015011215404114490871420.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015011215404114490871420.0.0.0_ep2d_diff_3scan_trace_p2_20150112153840_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0012524182/20150112_3587862/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015011215404114490771419.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2015011215404114490771419.0.0.0_ep2d_diff_3scan_trace_p2_20150112153840_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0012524182/20150112_3587862/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2015011215545061461682748.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2015011215545061461682748.0.0.0_t1_se_r_tra_KM_20150112153840_14.nii.gz'},
 13726250: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0013726250/20161115_4163094/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016111513570850700958667.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016111513570850700958667.0.0.0_ep2d_diff_3scan_trace_p2_20161115135255_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0013726250/20161115_4163094/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016111513570850700858666.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2016111513570850700858666.0.0.0_ep2d_diff_3scan_trace_p2_20161115135255_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0013726250/20161115_4163094/Tirm_tra_fs_TI_2500__1.3.12.2.1107.5.2.30.27272.201611151359397741760718.0.0.0/Tirm_tra_fs_TI_2500_1.3.12.2.1107.5.2.30.27272.201611151359397741760718.0.0.0_Tirm_tra_fs_TI_2500_20161115135255_4.nii.gz'},
 10957448: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0010957448/20120428_2900621/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.201204280936576983508645.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.201204280936576983508645.0.0.0_ep2d_diff_3scan_trace_p2_20120428093502_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0010957448/20120428_2900621/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.201204280936576983308644.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.201204280936576983308644.0.0.0_ep2d_diff_3scan_trace_p2_20120428093502_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0010957448/20120428_2900621/t2_blade_tra__1.3.12.2.1107.5.2.30.27272.2012042809393419148610862.0.0.0/t2_blade_tra_1.3.12.2.1107.5.2.30.27272.2012042809393419148610862.0.0.0_t2_blade_tra_20120428093502_4.nii.gz'},
 5768640: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0005768640/20150416_3663784/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015041607244246524101339.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015041607244246524101339.0.0.0_ep2d_diff_3scan_trace_p2_20150416072316_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0005768640/20150416_3663784/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015041607244246524001338.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2015041607244246524001338.0.0.0_ep2d_diff_3scan_trace_p2_20150416072316_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0005768640/20150416_3663784/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2015041607382548399912660.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2015041607382548399912660.0.0.0_t1_se_r_tra_KM_20150416072316_14.nii.gz'},
 4751884: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0004751884/20160825_4085988/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016082505265456580980765.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016082505265456580980765.0.0.0_ep2d_diff_3scan_trace_p2_20160825052535_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0004751884/20160825_4085988/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016082505265456580880764.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2016082505265456580880764.0.0.0_ep2d_diff_3scan_trace_p2_20160825052535_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0004751884/20160825_4085988/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2016082505401510906191940.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2016082505401510906191940.0.0.0_t1_se_r_tra_KM_20160825052535_12.nii.gz'},
 13806831: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0013806831/20161231_4205208/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016123103171570886101345.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016123103171570886101345.0.0.0_ep2d_diff_3scan_trace_p2_20161231031314_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0013806831/20161231_4205208/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016123103171570886001344.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2016123103171570886001344.0.0.0_ep2d_diff_3scan_trace_p2_20161231031314_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0013806831/20161231_4205208/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2016123103403826978614386.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2016123103403826978614386.0.0.0_t1_se_r_tra_KM_20161231031314_15.nii.gz'},
 13561340: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0013561340/20160814_4075674/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016081423232347130234856.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016081423232347130234856.0.0.0_ep2d_diff_3scan_trace_p2_20160814232122_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0013561340/20160814_4075674/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2016081423232347130034855.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2016081423232347130034855.0.0.0_ep2d_diff_3scan_trace_p2_20160814232122_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0013561340/20160814_4075674/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2016081423401756138141592.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2016081423401756138141592.0.0.0_t1_se_r_tra_KM_20160814232122_22.nii.gz'},
 911666: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0000911666/20170318_4279828/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017031803434419578756163.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2017031803434419578756163.0.0.0_ep2d_diff_3scan_trace_p2_20170318034215_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0000911666/20170318_4279828/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2017031803434419578656162.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2017031803434419578656162.0.0.0_ep2d_diff_3scan_trace_p2_20170318034215_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0000911666/20170318_4279828/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2017031803570532417566553.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2017031803570532417566553.0.0.0_t1_se_r_tra_KM_20170318034215_14.nii.gz'},
 11420316: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0011420316/20130204_3078550/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2013020411064122454430395.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2013020411064122454430395.0.0.0_ep2d_diff_M128_b0_1000_DIN_20130204110226_4.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0011420316/20130204_3078550/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40270.2013020411064122454030394.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40270.2013020411064122454030394.0.0.0_ep2d_diff_M128_b0_1000_DIN_20130204110226_3.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0011420316/20130204_3078550/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.2013020411212991837441954.0.0.0/t1_fl2d_tra_1.3.12.2.1107.5.2.36.40270.2013020411212991837441954.0.0.0_t1_fl2d_tra_20130204110226_15.nii.gz'},
 8505020: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0008505020/20161024_4142199/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.201610241554179766291780.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40186.201610241554179766291780.0.0.0_ep2d_diff_M128_b0_1000_DIN_20161024155220_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0008505020/20161024_4142199/ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2.36.40186.201610241554179766191779.0.0.0/ep2d_diff_M128_b0_1000_DIN_1.3.12.2.1107.5.2.36.40186.201610241554179766191779.0.0.0_ep2d_diff_M128_b0_1000_DIN_20161024155220_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0008505020/20161024_4142199/t1_fl2d_tra__1.3.12.2.1107.5.2.36.40186.2016102416073279025003279.0.0.0/t1_fl2d_tra_1.3.12.2.1107.5.2.36.40186.2016102416073279025003279.0.0.0_t1_fl2d_tra_20161024155220_14.nii.gz'},
 12752479: {'adc': '/home/bule/berner_daten_analyse/data/nifti/0012752479/20150509_3683394/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015050911245686910728617.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015050911245686910728617.0.0.0_ep2d_diff_3scan_trace_p2_20150509112322_3.nii.gz',
  'dwi': '/home/bule/berner_daten_analyse/data/nifti/0012752479/20150509_3683394/ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30.27272.2015050911245686910628616.0.0.0/ep2d_diff_3scan_trace_p2_1.3.12.2.1107.5.2.30.27272.2015050911245686910628616.0.0.0_ep2d_diff_3scan_trace_p2_20150509112322_2.nii.gz',
  'anatomic': '/home/bule/berner_daten_analyse/data/nifti/0012752479/20150509_3683394/t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.2015050911432419210041249.0.0.0/t1_se_r_tra_KM_1.3.12.2.1107.5.2.30.27272.2015050911432419210041249.0.0.0_t1_se_r_tra_KM_20150509112322_14.nii.gz'},

In [40]:
merge_adc_dwi = pd.DataFrame.from_dict(dict_paths_new, orient='index').reset_index()

# rename columns
merge_adc_dwi = merge_adc_dwi.rename(columns={'index': 'Patient_ID', 
                        'dwi': 'Full_Path_dwi', 
                        'adc': 'Full_Path_adc', 
                        'anatomic': 'Full_Path_anatomic'})

merge_adc_dwi.to_csv(os.path.join(DATA_PATH,'merge_adc_dwi.csv'), index=False)